//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.18444
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace HydroDesktop.Plugins.DataDownload {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class MessageStrings {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal MessageStrings() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("HydroDesktop.Plugins.DataDownload.MessageStrings", typeof(MessageStrings).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Deselect All.
        /// </summary>
        internal static string Deselect {
            get {
                return ResourceManager.GetString("Deselect", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Download.
        /// </summary>
        internal static string Download {
            get {
                return ResourceManager.GetString("Download", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Download Selected.
        /// </summary>
        internal static string Download_Selected {
            get {
                return ResourceManager.GetString("Download_Selected", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Download tool.
        /// </summary>
        internal static string Download_Tools_Group {
            get {
                return ResourceManager.GetString("Download_Tools_Group", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Download Settings.
        /// </summary>
        internal static string DownloadSettings {
            get {
                return ResourceManager.GetString("DownloadSettings", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Click to download all selected series.
        /// </summary>
        internal static string DownloadTooTip {
            get {
                return ResourceManager.GetString("DownloadTooTip", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Identify.
        /// </summary>
        internal static string Identify {
            get {
                return ResourceManager.GetString("Identify", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Map Tool.
        /// </summary>
        internal static string Map_Tools_Group {
            get {
                return ResourceManager.GetString("Map_Tools_Group", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Metadata.
        /// </summary>
        internal static string Metadata {
            get {
                return ResourceManager.GetString("Metadata", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Pan.
        /// </summary>
        internal static string Pan {
            get {
                return ResourceManager.GetString("Pan", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Search Results.
        /// </summary>
        internal static string Results {
            get {
                return ResourceManager.GetString("Results", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Search.
        /// </summary>
        internal static string Search {
            get {
                return ResourceManager.GetString("Search", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Search Results tool.
        /// </summary>
        internal static string Search_Results_Tools_Group {
            get {
                return ResourceManager.GetString("Search_Results_Tools_Group", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Select.
        /// </summary>
        internal static string Select {
            get {
                return ResourceManager.GetString("Select", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Show Popups.
        /// </summary>
        internal static string ShowPopups {
            get {
                return ResourceManager.GetString("ShowPopups", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Update.
        /// </summary>
        internal static string Update {
            get {
                return ResourceManager.GetString("Update", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to View.
        /// </summary>
        internal static string View_Group {
            get {
                return ResourceManager.GetString("View_Group", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Zoom.
        /// </summary>
        internal static string Zoom_Group {
            get {
                return ResourceManager.GetString("Zoom_Group", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to In.
        /// </summary>
        internal static string Zoom_In {
            get {
                return ResourceManager.GetString("Zoom_In", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Zoom In.
        /// </summary>
        internal static string Zoom_In_Tooltip {
            get {
                return ResourceManager.GetString("Zoom_In_Tooltip", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Next.
        /// </summary>
        internal static string Zoom_Next {
            get {
                return ResourceManager.GetString("Zoom_Next", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Zoom Next.
        /// </summary>
        internal static string Zoom_Next_Tooltip {
            get {
                return ResourceManager.GetString("Zoom_Next_Tooltip", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Out.
        /// </summary>
        internal static string Zoom_Out {
            get {
                return ResourceManager.GetString("Zoom_Out", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Zoom Out.
        /// </summary>
        internal static string Zoom_Out_Tooltip {
            get {
                return ResourceManager.GetString("Zoom_Out_Tooltip", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Previous.
        /// </summary>
        internal static string Zoom_Previous {
            get {
                return ResourceManager.GetString("Zoom_Previous", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Zoom Previous.
        /// </summary>
        internal static string Zoom_Previous_Tooltip {
            get {
                return ResourceManager.GetString("Zoom_Previous_Tooltip", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to To Extents.
        /// </summary>
        internal static string Zoom_To_Extents {
            get {
                return ResourceManager.GetString("Zoom_To_Extents", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Zoom to Extents.
        /// </summary>
        internal static string Zoom_To_Extents_Tooltip {
            get {
                return ResourceManager.GetString("Zoom_To_Extents_Tooltip", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Zoom To Layer.
        /// </summary>
        internal static string Zoom_To_Layer {
            get {
                return ResourceManager.GetString("Zoom_To_Layer", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Zoom To Selection.
        /// </summary>
        internal static string Zoom_To_Selection {
            get {
                return ResourceManager.GetString("Zoom_To_Selection", resourceCulture);
            }
        }
    }
}
