//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.18444
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace HydroDesktop.Plugins.Search {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class MessageStrings {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal MessageStrings() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("HydroDesktop.Plugins.Search.MessageStrings", typeof(MessageStrings).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to     Select Multiple Keywords.
        /// </summary>
        internal static string Add_More_Keywords {
            get {
                return ResourceManager.GetString("Add_More_Keywords", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Search Area.
        /// </summary>
        internal static string Area {
            get {
                return ResourceManager.GetString("Area", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Continue search.
        /// </summary>
        internal static string Continue_Search {
            get {
                return ResourceManager.GetString("Continue_Search", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Controls.
        /// </summary>
        internal static string Controls {
            get {
                return ResourceManager.GetString("Controls", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Current View.
        /// </summary>
        internal static string Current_View {
            get {
                return ResourceManager.GetString("Current_View", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Current view is too large. Search can take a long time. Do you want to continue?.
        /// </summary>
        internal static string Current_View_Large_Msg {
            get {
                return ResourceManager.GetString("Current_View_Large_Msg", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Use the current view extents of the map as the search area..
        /// </summary>
        internal static string Current_View_Tooltip {
            get {
                return ResourceManager.GetString("Current_View_Tooltip", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Clear Selection.
        /// </summary>
        internal static string Deselect_All {
            get {
                return ResourceManager.GetString("Deselect_All", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Deselect all features.
        /// </summary>
        internal static string Deselect_All_Tooltip {
            get {
                return ResourceManager.GetString("Deselect_All_Tooltip", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Draw Box.
        /// </summary>
        internal static string Draw_Box {
            get {
                return ResourceManager.GetString("Draw_Box", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Draw a rectangle for your search area.
        /// </summary>
        internal static string Draw_Box_Tooltip {
            get {
                return ResourceManager.GetString("Draw_Box_Tooltip", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to    Draw    Rectangle.
        /// </summary>
        internal static string Draw_Rectangle {
            get {
                return ResourceManager.GetString("Draw_Rectangle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to End Date.
        /// </summary>
        internal static string End_Date {
            get {
                return ResourceManager.GetString("End_Date", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Error.
        /// </summary>
        internal static string Error {
            get {
                return ResourceManager.GetString("Error", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Information.
        /// </summary>
        internal static string Information {
            get {
                return ResourceManager.GetString("Information", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Keyword.
        /// </summary>
        internal static string Keyword {
            get {
                return ResourceManager.GetString("Keyword", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Show Keyword Ontology Tree.
        /// </summary>
        internal static string Keyword_Tooltip {
            get {
                return ResourceManager.GetString("Keyword_Tooltip", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Pan.
        /// </summary>
        internal static string Pan {
            get {
                return ResourceManager.GetString("Pan", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Run Search.
        /// </summary>
        internal static string Run_Search {
            get {
                return ResourceManager.GetString("Run_Search", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Run Search based on selected criteria.
        /// </summary>
        internal static string Run_Search_Tooltip {
            get {
                return ResourceManager.GetString("Run_Search_Tooltip", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Search.
        /// </summary>
        internal static string Search {
            get {
                return ResourceManager.GetString("Search", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Select by Attribute.
        /// </summary>
        internal static string Select_By_Attribute {
            get {
                return ResourceManager.GetString("Select_By_Attribute", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Select Data Sources.
        /// </summary>
        internal static string Select_Data_Sources {
            get {
                return ResourceManager.GetString("Select_Data_Sources", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Select data sources (All web services selected).
        /// </summary>
        internal static string Select_Data_Sources_Tooltip {
            get {
                return ResourceManager.GetString("Select_Data_Sources_Tooltip", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Select Dates.
        /// </summary>
        internal static string Select_Dates {
            get {
                return ResourceManager.GetString("Select_Dates", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Select Features.
        /// </summary>
        internal static string Select_Features {
            get {
                return ResourceManager.GetString("Select_Features", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Click in the map to select features for searching.
        /// </summary>
        internal static string Select_Features_Tooltip {
            get {
                return ResourceManager.GetString("Select_Features_Tooltip", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Select Polygons.
        /// </summary>
        internal static string Select_Polygons {
            get {
                return ResourceManager.GetString("Select_Polygons", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Select Region.
        /// </summary>
        internal static string Select_Polygons_Tooltip {
            get {
                return ResourceManager.GetString("Select_Polygons_Tooltip", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Start Date.
        /// </summary>
        internal static string Start_Date {
            get {
                return ResourceManager.GetString("Start_Date", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Start Date validation.
        /// </summary>
        internal static string Start_Date_Validation {
            get {
                return ResourceManager.GetString("Start_Date_Validation", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to End Date must be greater than Start Date..
        /// </summary>
        internal static string Start_Date_Validation_Msg {
            get {
                return ResourceManager.GetString("Start_Date_Validation_Msg", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Time Range.
        /// </summary>
        internal static string Time_Range {
            get {
                return ResourceManager.GetString("Time_Range", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to  End.
        /// </summary>
        internal static string TimeRange_End {
            get {
                return ResourceManager.GetString("TimeRange_End", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Start.
        /// </summary>
        internal static string TimeRange_Start {
            get {
                return ResourceManager.GetString("TimeRange_Start", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Type-in a Keyword.
        /// </summary>
        internal static string Type_In_Keyword {
            get {
                return ResourceManager.GetString("Type_In_Keyword", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to In.
        /// </summary>
        internal static string Zoom_In {
            get {
                return ResourceManager.GetString("Zoom_In", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Zoom In.
        /// </summary>
        internal static string Zoom_In_Tooltip {
            get {
                return ResourceManager.GetString("Zoom_In_Tooltip", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Out.
        /// </summary>
        internal static string Zoom_Out {
            get {
                return ResourceManager.GetString("Zoom_Out", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Zoom Out.
        /// </summary>
        internal static string Zoom_Out_Tooltip {
            get {
                return ResourceManager.GetString("Zoom_Out_Tooltip", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Zoom to Selection.
        /// </summary>
        internal static string Zoom_Selected {
            get {
                return ResourceManager.GetString("Zoom_Selected", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Zoom to selected features.
        /// </summary>
        internal static string Zoom_Selected_Tooltip {
            get {
                return ResourceManager.GetString("Zoom_Selected_Tooltip", resourceCulture);
            }
        }
    }
}
