using System.ComponentModel;

namespace HydroDesktop.Interfaces.ObjectModel
{
    /// <summary>
    /// Used to populate the ValueType field in the Variables table
    /// </summary>
    /// <remarks>
    /// See http://his.cuahsi.org/mastercvreg/edit_cv11.aspx?tbl=ValueTypeCV&id=805577908
    /// </remarks>
    public enum ValueTypeCV
    {
        /// <summary>
        /// The value type is unknown.
        /// </summary>
        [Description("Unknown")]
        Unknown = 0,

        /// <summary>
        /// A value used as part of the calibration of an instrument at a particular time.
        /// </summary>
        [Description("Calibration Value")]
        CalibrationValue = 1,

        /// <summary>
        /// Value that is directly derived from an observation or set of observations.
        /// </summary>
        [Description("Derived Value")]
        DerivedValue = 2,

        /// <summary>
        /// Observation of a variable using a field instrument.
        /// </summary>
        [Description("Field Observation")]
        FieldObservation = 3,

        /// <summary>
        /// Values generated by a simulation model.
        /// </summary>
        [Description("Model Simulation Result")]
        ModelSimulationResult = 4,

        /// <summary>
        /// Observation that is the result of analyzing a sample in a laboratory.
        /// </summary>
        [Description("Sample")]
        Sample = 5,
    }
}
