"""Subclass of MyFrame1, which is generated by wxFormBuilder."""

import wx
import GetShapefiles
import hydrosharedownload
import sys

# Implementing MyFrame1
class GetShapefilesFromHydroShareMyFrame1( GetShapefiles.MyFrame1 ):
    hydrosharedownloader = None

    def __init__( self, parent ):
        GetShapefiles.MyFrame1.__init__( self, parent )
        self.hydrosharedownloader = hydrosharedownload.HydroshareDownloader()
        
    def populateList(self):
        filtered_files = self.hydrosharedownloader.retrieveList()
        i=0
        for item in filtered_files:
            self.lst_AvailableItems.Insert(item, i)
            i+=1
    
    # Handlers for MyFrame1 events.
    def clk_Refresh( self, event):
        self.lst_AvailableItems.Clear()
        self.populateList()
    
    def clk_Cancel( self, event ):
        self.Close()
    
    def clk_GetData( self, event ):
        if self.lst_AvailableItems.GetSelection() >= 0:
            self.hydrosharedownloader.downloadFile(self.lst_AvailableItems.GetString(self.lst_AvailableItems.GetSelection()))
    
def open():
    app = wx.App(0)
    
    frame = GetShapefilesFromHydroShareMyFrame1(None)
    frame.Show()
    frame.populateList()
    if len(sys.argv) > 1:
        frame.hydrosharedownloader.file_path = sys.argv[1]
    app.MainLoop()
    
if __name__ == '__main__':
    open()
    