//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.544
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace HydroDesktop.Data.ODMCVServiceClient.ServiceReference.ODMCV {
    
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.ServiceContractAttribute(Namespace="http://his.cuahsi.org/his/1.1/ws/", ConfigurationName="ServiceReference.ODMCV.ODMCVServiceSoap")]
    internal interface ODMCVServiceSoap {
        
        // CODEGEN: Generating message contract since element name GetCensorCodeCVResult from namespace http://his.cuahsi.org/his/1.1/ws/ is not marked nillable
        [System.ServiceModel.OperationContractAttribute(Action="http://his.cuahsi.org/his/1.1/ws/GetCensorCodeCV", ReplyAction="*")]
        HydroDesktop.Data.ODMCVServiceClient.ServiceReference.ODMCV.GetCensorCodeCVResponse GetCensorCodeCV(HydroDesktop.Data.ODMCVServiceClient.ServiceReference.ODMCV.GetCensorCodeCVRequest request);
        
        // CODEGEN: Generating message contract since element name GetDataTypeCVResult from namespace http://his.cuahsi.org/his/1.1/ws/ is not marked nillable
        [System.ServiceModel.OperationContractAttribute(Action="http://his.cuahsi.org/his/1.1/ws/GetDataTypeCV", ReplyAction="*")]
        HydroDesktop.Data.ODMCVServiceClient.ServiceReference.ODMCV.GetDataTypeCVResponse GetDataTypeCV(HydroDesktop.Data.ODMCVServiceClient.ServiceReference.ODMCV.GetDataTypeCVRequest request);
        
        // CODEGEN: Generating message contract since element name GetGeneralCategoryCVResult from namespace http://his.cuahsi.org/his/1.1/ws/ is not marked nillable
        [System.ServiceModel.OperationContractAttribute(Action="http://his.cuahsi.org/his/1.1/ws/GetGeneralCategoryCV", ReplyAction="*")]
        HydroDesktop.Data.ODMCVServiceClient.ServiceReference.ODMCV.GetGeneralCategoryCVResponse GetGeneralCategoryCV(HydroDesktop.Data.ODMCVServiceClient.ServiceReference.ODMCV.GetGeneralCategoryCVRequest request);
        
        // CODEGEN: Generating message contract since element name GetSampleMediumCVResult from namespace http://his.cuahsi.org/his/1.1/ws/ is not marked nillable
        [System.ServiceModel.OperationContractAttribute(Action="http://his.cuahsi.org/his/1.1/ws/GetSampleMediumCV", ReplyAction="*")]
        HydroDesktop.Data.ODMCVServiceClient.ServiceReference.ODMCV.GetSampleMediumCVResponse GetSampleMediumCV(HydroDesktop.Data.ODMCVServiceClient.ServiceReference.ODMCV.GetSampleMediumCVRequest request);
        
        // CODEGEN: Generating message contract since element name GetSampleTypeCVResult from namespace http://his.cuahsi.org/his/1.1/ws/ is not marked nillable
        [System.ServiceModel.OperationContractAttribute(Action="http://his.cuahsi.org/his/1.1/ws/GetSampleTypeCV", ReplyAction="*")]
        HydroDesktop.Data.ODMCVServiceClient.ServiceReference.ODMCV.GetSampleTypeCVResponse GetSampleTypeCV(HydroDesktop.Data.ODMCVServiceClient.ServiceReference.ODMCV.GetSampleTypeCVRequest request);
        
        // CODEGEN: Generating message contract since element name GetTopicCategoryCVResult from namespace http://his.cuahsi.org/his/1.1/ws/ is not marked nillable
        [System.ServiceModel.OperationContractAttribute(Action="http://his.cuahsi.org/his/1.1/ws/GetTopicCategoryCV", ReplyAction="*")]
        HydroDesktop.Data.ODMCVServiceClient.ServiceReference.ODMCV.GetTopicCategoryCVResponse GetTopicCategoryCV(HydroDesktop.Data.ODMCVServiceClient.ServiceReference.ODMCV.GetTopicCategoryCVRequest request);
        
        // CODEGEN: Generating message contract since element name GetValueTypeCVResult from namespace http://his.cuahsi.org/his/1.1/ws/ is not marked nillable
        [System.ServiceModel.OperationContractAttribute(Action="http://his.cuahsi.org/his/1.1/ws/GetValueTypeCV", ReplyAction="*")]
        HydroDesktop.Data.ODMCVServiceClient.ServiceReference.ODMCV.GetValueTypeCVResponse GetValueTypeCV(HydroDesktop.Data.ODMCVServiceClient.ServiceReference.ODMCV.GetValueTypeCVRequest request);
        
        // CODEGEN: Generating message contract since element name GetVariableNameCVResult from namespace http://his.cuahsi.org/his/1.1/ws/ is not marked nillable
        [System.ServiceModel.OperationContractAttribute(Action="http://his.cuahsi.org/his/1.1/ws/GetVariableNameCV", ReplyAction="*")]
        HydroDesktop.Data.ODMCVServiceClient.ServiceReference.ODMCV.GetVariableNameCVResponse GetVariableNameCV(HydroDesktop.Data.ODMCVServiceClient.ServiceReference.ODMCV.GetVariableNameCVRequest request);
        
        // CODEGEN: Generating message contract since element name GetVerticalDatumCVResult from namespace http://his.cuahsi.org/his/1.1/ws/ is not marked nillable
        [System.ServiceModel.OperationContractAttribute(Action="http://his.cuahsi.org/his/1.1/ws/GetVerticalDatumCV", ReplyAction="*")]
        HydroDesktop.Data.ODMCVServiceClient.ServiceReference.ODMCV.GetVerticalDatumCVResponse GetVerticalDatumCV(HydroDesktop.Data.ODMCVServiceClient.ServiceReference.ODMCV.GetVerticalDatumCVRequest request);
        
        // CODEGEN: Generating message contract since element name GetSpatialReferencesResult from namespace http://his.cuahsi.org/his/1.1/ws/ is not marked nillable
        [System.ServiceModel.OperationContractAttribute(Action="http://his.cuahsi.org/his/1.1/ws/GetSpatialReferences", ReplyAction="*")]
        HydroDesktop.Data.ODMCVServiceClient.ServiceReference.ODMCV.GetSpatialReferencesResponse GetSpatialReferences(HydroDesktop.Data.ODMCVServiceClient.ServiceReference.ODMCV.GetSpatialReferencesRequest request);
        
        // CODEGEN: Generating message contract since element name GetUnitsResult from namespace http://his.cuahsi.org/his/1.1/ws/ is not marked nillable
        [System.ServiceModel.OperationContractAttribute(Action="http://his.cuahsi.org/his/1.1/ws/GetUnits", ReplyAction="*")]
        HydroDesktop.Data.ODMCVServiceClient.ServiceReference.ODMCV.GetUnitsResponse GetUnits(HydroDesktop.Data.ODMCVServiceClient.ServiceReference.ODMCV.GetUnitsRequest request);
        
        // CODEGEN: Generating message contract since element name GetSpeciationCVResult from namespace http://his.cuahsi.org/his/1.1/ws/ is not marked nillable
        [System.ServiceModel.OperationContractAttribute(Action="http://his.cuahsi.org/his/1.1/ws/GetSpeciationCV", ReplyAction="*")]
        HydroDesktop.Data.ODMCVServiceClient.ServiceReference.ODMCV.GetSpeciationCVResponse GetSpeciationCV(HydroDesktop.Data.ODMCVServiceClient.ServiceReference.ODMCV.GetSpeciationCVRequest request);
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    internal partial class GetCensorCodeCVRequest {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="GetCensorCodeCV", Namespace="http://his.cuahsi.org/his/1.1/ws/", Order=0)]
        public HydroDesktop.Data.ODMCVServiceClient.ServiceReference.ODMCV.GetCensorCodeCVRequestBody Body;
        
        public GetCensorCodeCVRequest() {
        }
        
        public GetCensorCodeCVRequest(HydroDesktop.Data.ODMCVServiceClient.ServiceReference.ODMCV.GetCensorCodeCVRequestBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute()]
    internal partial class GetCensorCodeCVRequestBody {
        
        public GetCensorCodeCVRequestBody() {
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    internal partial class GetCensorCodeCVResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="GetCensorCodeCVResponse", Namespace="http://his.cuahsi.org/his/1.1/ws/", Order=0)]
        public HydroDesktop.Data.ODMCVServiceClient.ServiceReference.ODMCV.GetCensorCodeCVResponseBody Body;
        
        public GetCensorCodeCVResponse() {
        }
        
        public GetCensorCodeCVResponse(HydroDesktop.Data.ODMCVServiceClient.ServiceReference.ODMCV.GetCensorCodeCVResponseBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://his.cuahsi.org/his/1.1/ws/")]
    internal partial class GetCensorCodeCVResponseBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public string GetCensorCodeCVResult;
        
        public GetCensorCodeCVResponseBody() {
        }
        
        public GetCensorCodeCVResponseBody(string GetCensorCodeCVResult) {
            this.GetCensorCodeCVResult = GetCensorCodeCVResult;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    internal partial class GetDataTypeCVRequest {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="GetDataTypeCV", Namespace="http://his.cuahsi.org/his/1.1/ws/", Order=0)]
        public HydroDesktop.Data.ODMCVServiceClient.ServiceReference.ODMCV.GetDataTypeCVRequestBody Body;
        
        public GetDataTypeCVRequest() {
        }
        
        public GetDataTypeCVRequest(HydroDesktop.Data.ODMCVServiceClient.ServiceReference.ODMCV.GetDataTypeCVRequestBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute()]
    internal partial class GetDataTypeCVRequestBody {
        
        public GetDataTypeCVRequestBody() {
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    internal partial class GetDataTypeCVResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="GetDataTypeCVResponse", Namespace="http://his.cuahsi.org/his/1.1/ws/", Order=0)]
        public HydroDesktop.Data.ODMCVServiceClient.ServiceReference.ODMCV.GetDataTypeCVResponseBody Body;
        
        public GetDataTypeCVResponse() {
        }
        
        public GetDataTypeCVResponse(HydroDesktop.Data.ODMCVServiceClient.ServiceReference.ODMCV.GetDataTypeCVResponseBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://his.cuahsi.org/his/1.1/ws/")]
    internal partial class GetDataTypeCVResponseBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public string GetDataTypeCVResult;
        
        public GetDataTypeCVResponseBody() {
        }
        
        public GetDataTypeCVResponseBody(string GetDataTypeCVResult) {
            this.GetDataTypeCVResult = GetDataTypeCVResult;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    internal partial class GetGeneralCategoryCVRequest {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="GetGeneralCategoryCV", Namespace="http://his.cuahsi.org/his/1.1/ws/", Order=0)]
        public HydroDesktop.Data.ODMCVServiceClient.ServiceReference.ODMCV.GetGeneralCategoryCVRequestBody Body;
        
        public GetGeneralCategoryCVRequest() {
        }
        
        public GetGeneralCategoryCVRequest(HydroDesktop.Data.ODMCVServiceClient.ServiceReference.ODMCV.GetGeneralCategoryCVRequestBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute()]
    internal partial class GetGeneralCategoryCVRequestBody {
        
        public GetGeneralCategoryCVRequestBody() {
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    internal partial class GetGeneralCategoryCVResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="GetGeneralCategoryCVResponse", Namespace="http://his.cuahsi.org/his/1.1/ws/", Order=0)]
        public HydroDesktop.Data.ODMCVServiceClient.ServiceReference.ODMCV.GetGeneralCategoryCVResponseBody Body;
        
        public GetGeneralCategoryCVResponse() {
        }
        
        public GetGeneralCategoryCVResponse(HydroDesktop.Data.ODMCVServiceClient.ServiceReference.ODMCV.GetGeneralCategoryCVResponseBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://his.cuahsi.org/his/1.1/ws/")]
    internal partial class GetGeneralCategoryCVResponseBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public string GetGeneralCategoryCVResult;
        
        public GetGeneralCategoryCVResponseBody() {
        }
        
        public GetGeneralCategoryCVResponseBody(string GetGeneralCategoryCVResult) {
            this.GetGeneralCategoryCVResult = GetGeneralCategoryCVResult;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    internal partial class GetSampleMediumCVRequest {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="GetSampleMediumCV", Namespace="http://his.cuahsi.org/his/1.1/ws/", Order=0)]
        public HydroDesktop.Data.ODMCVServiceClient.ServiceReference.ODMCV.GetSampleMediumCVRequestBody Body;
        
        public GetSampleMediumCVRequest() {
        }
        
        public GetSampleMediumCVRequest(HydroDesktop.Data.ODMCVServiceClient.ServiceReference.ODMCV.GetSampleMediumCVRequestBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute()]
    internal partial class GetSampleMediumCVRequestBody {
        
        public GetSampleMediumCVRequestBody() {
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    internal partial class GetSampleMediumCVResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="GetSampleMediumCVResponse", Namespace="http://his.cuahsi.org/his/1.1/ws/", Order=0)]
        public HydroDesktop.Data.ODMCVServiceClient.ServiceReference.ODMCV.GetSampleMediumCVResponseBody Body;
        
        public GetSampleMediumCVResponse() {
        }
        
        public GetSampleMediumCVResponse(HydroDesktop.Data.ODMCVServiceClient.ServiceReference.ODMCV.GetSampleMediumCVResponseBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://his.cuahsi.org/his/1.1/ws/")]
    internal partial class GetSampleMediumCVResponseBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public string GetSampleMediumCVResult;
        
        public GetSampleMediumCVResponseBody() {
        }
        
        public GetSampleMediumCVResponseBody(string GetSampleMediumCVResult) {
            this.GetSampleMediumCVResult = GetSampleMediumCVResult;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    internal partial class GetSampleTypeCVRequest {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="GetSampleTypeCV", Namespace="http://his.cuahsi.org/his/1.1/ws/", Order=0)]
        public HydroDesktop.Data.ODMCVServiceClient.ServiceReference.ODMCV.GetSampleTypeCVRequestBody Body;
        
        public GetSampleTypeCVRequest() {
        }
        
        public GetSampleTypeCVRequest(HydroDesktop.Data.ODMCVServiceClient.ServiceReference.ODMCV.GetSampleTypeCVRequestBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute()]
    internal partial class GetSampleTypeCVRequestBody {
        
        public GetSampleTypeCVRequestBody() {
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    internal partial class GetSampleTypeCVResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="GetSampleTypeCVResponse", Namespace="http://his.cuahsi.org/his/1.1/ws/", Order=0)]
        public HydroDesktop.Data.ODMCVServiceClient.ServiceReference.ODMCV.GetSampleTypeCVResponseBody Body;
        
        public GetSampleTypeCVResponse() {
        }
        
        public GetSampleTypeCVResponse(HydroDesktop.Data.ODMCVServiceClient.ServiceReference.ODMCV.GetSampleTypeCVResponseBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://his.cuahsi.org/his/1.1/ws/")]
    internal partial class GetSampleTypeCVResponseBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public string GetSampleTypeCVResult;
        
        public GetSampleTypeCVResponseBody() {
        }
        
        public GetSampleTypeCVResponseBody(string GetSampleTypeCVResult) {
            this.GetSampleTypeCVResult = GetSampleTypeCVResult;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    internal partial class GetTopicCategoryCVRequest {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="GetTopicCategoryCV", Namespace="http://his.cuahsi.org/his/1.1/ws/", Order=0)]
        public HydroDesktop.Data.ODMCVServiceClient.ServiceReference.ODMCV.GetTopicCategoryCVRequestBody Body;
        
        public GetTopicCategoryCVRequest() {
        }
        
        public GetTopicCategoryCVRequest(HydroDesktop.Data.ODMCVServiceClient.ServiceReference.ODMCV.GetTopicCategoryCVRequestBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute()]
    internal partial class GetTopicCategoryCVRequestBody {
        
        public GetTopicCategoryCVRequestBody() {
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    internal partial class GetTopicCategoryCVResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="GetTopicCategoryCVResponse", Namespace="http://his.cuahsi.org/his/1.1/ws/", Order=0)]
        public HydroDesktop.Data.ODMCVServiceClient.ServiceReference.ODMCV.GetTopicCategoryCVResponseBody Body;
        
        public GetTopicCategoryCVResponse() {
        }
        
        public GetTopicCategoryCVResponse(HydroDesktop.Data.ODMCVServiceClient.ServiceReference.ODMCV.GetTopicCategoryCVResponseBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://his.cuahsi.org/his/1.1/ws/")]
    internal partial class GetTopicCategoryCVResponseBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public string GetTopicCategoryCVResult;
        
        public GetTopicCategoryCVResponseBody() {
        }
        
        public GetTopicCategoryCVResponseBody(string GetTopicCategoryCVResult) {
            this.GetTopicCategoryCVResult = GetTopicCategoryCVResult;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    internal partial class GetValueTypeCVRequest {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="GetValueTypeCV", Namespace="http://his.cuahsi.org/his/1.1/ws/", Order=0)]
        public HydroDesktop.Data.ODMCVServiceClient.ServiceReference.ODMCV.GetValueTypeCVRequestBody Body;
        
        public GetValueTypeCVRequest() {
        }
        
        public GetValueTypeCVRequest(HydroDesktop.Data.ODMCVServiceClient.ServiceReference.ODMCV.GetValueTypeCVRequestBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute()]
    internal partial class GetValueTypeCVRequestBody {
        
        public GetValueTypeCVRequestBody() {
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    internal partial class GetValueTypeCVResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="GetValueTypeCVResponse", Namespace="http://his.cuahsi.org/his/1.1/ws/", Order=0)]
        public HydroDesktop.Data.ODMCVServiceClient.ServiceReference.ODMCV.GetValueTypeCVResponseBody Body;
        
        public GetValueTypeCVResponse() {
        }
        
        public GetValueTypeCVResponse(HydroDesktop.Data.ODMCVServiceClient.ServiceReference.ODMCV.GetValueTypeCVResponseBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://his.cuahsi.org/his/1.1/ws/")]
    internal partial class GetValueTypeCVResponseBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public string GetValueTypeCVResult;
        
        public GetValueTypeCVResponseBody() {
        }
        
        public GetValueTypeCVResponseBody(string GetValueTypeCVResult) {
            this.GetValueTypeCVResult = GetValueTypeCVResult;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    internal partial class GetVariableNameCVRequest {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="GetVariableNameCV", Namespace="http://his.cuahsi.org/his/1.1/ws/", Order=0)]
        public HydroDesktop.Data.ODMCVServiceClient.ServiceReference.ODMCV.GetVariableNameCVRequestBody Body;
        
        public GetVariableNameCVRequest() {
        }
        
        public GetVariableNameCVRequest(HydroDesktop.Data.ODMCVServiceClient.ServiceReference.ODMCV.GetVariableNameCVRequestBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute()]
    internal partial class GetVariableNameCVRequestBody {
        
        public GetVariableNameCVRequestBody() {
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    internal partial class GetVariableNameCVResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="GetVariableNameCVResponse", Namespace="http://his.cuahsi.org/his/1.1/ws/", Order=0)]
        public HydroDesktop.Data.ODMCVServiceClient.ServiceReference.ODMCV.GetVariableNameCVResponseBody Body;
        
        public GetVariableNameCVResponse() {
        }
        
        public GetVariableNameCVResponse(HydroDesktop.Data.ODMCVServiceClient.ServiceReference.ODMCV.GetVariableNameCVResponseBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://his.cuahsi.org/his/1.1/ws/")]
    internal partial class GetVariableNameCVResponseBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public string GetVariableNameCVResult;
        
        public GetVariableNameCVResponseBody() {
        }
        
        public GetVariableNameCVResponseBody(string GetVariableNameCVResult) {
            this.GetVariableNameCVResult = GetVariableNameCVResult;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    internal partial class GetVerticalDatumCVRequest {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="GetVerticalDatumCV", Namespace="http://his.cuahsi.org/his/1.1/ws/", Order=0)]
        public HydroDesktop.Data.ODMCVServiceClient.ServiceReference.ODMCV.GetVerticalDatumCVRequestBody Body;
        
        public GetVerticalDatumCVRequest() {
        }
        
        public GetVerticalDatumCVRequest(HydroDesktop.Data.ODMCVServiceClient.ServiceReference.ODMCV.GetVerticalDatumCVRequestBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute()]
    internal partial class GetVerticalDatumCVRequestBody {
        
        public GetVerticalDatumCVRequestBody() {
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    internal partial class GetVerticalDatumCVResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="GetVerticalDatumCVResponse", Namespace="http://his.cuahsi.org/his/1.1/ws/", Order=0)]
        public HydroDesktop.Data.ODMCVServiceClient.ServiceReference.ODMCV.GetVerticalDatumCVResponseBody Body;
        
        public GetVerticalDatumCVResponse() {
        }
        
        public GetVerticalDatumCVResponse(HydroDesktop.Data.ODMCVServiceClient.ServiceReference.ODMCV.GetVerticalDatumCVResponseBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://his.cuahsi.org/his/1.1/ws/")]
    internal partial class GetVerticalDatumCVResponseBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public string GetVerticalDatumCVResult;
        
        public GetVerticalDatumCVResponseBody() {
        }
        
        public GetVerticalDatumCVResponseBody(string GetVerticalDatumCVResult) {
            this.GetVerticalDatumCVResult = GetVerticalDatumCVResult;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    internal partial class GetSpatialReferencesRequest {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="GetSpatialReferences", Namespace="http://his.cuahsi.org/his/1.1/ws/", Order=0)]
        public HydroDesktop.Data.ODMCVServiceClient.ServiceReference.ODMCV.GetSpatialReferencesRequestBody Body;
        
        public GetSpatialReferencesRequest() {
        }
        
        public GetSpatialReferencesRequest(HydroDesktop.Data.ODMCVServiceClient.ServiceReference.ODMCV.GetSpatialReferencesRequestBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute()]
    internal partial class GetSpatialReferencesRequestBody {
        
        public GetSpatialReferencesRequestBody() {
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    internal partial class GetSpatialReferencesResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="GetSpatialReferencesResponse", Namespace="http://his.cuahsi.org/his/1.1/ws/", Order=0)]
        public HydroDesktop.Data.ODMCVServiceClient.ServiceReference.ODMCV.GetSpatialReferencesResponseBody Body;
        
        public GetSpatialReferencesResponse() {
        }
        
        public GetSpatialReferencesResponse(HydroDesktop.Data.ODMCVServiceClient.ServiceReference.ODMCV.GetSpatialReferencesResponseBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://his.cuahsi.org/his/1.1/ws/")]
    internal partial class GetSpatialReferencesResponseBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public string GetSpatialReferencesResult;
        
        public GetSpatialReferencesResponseBody() {
        }
        
        public GetSpatialReferencesResponseBody(string GetSpatialReferencesResult) {
            this.GetSpatialReferencesResult = GetSpatialReferencesResult;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    internal partial class GetUnitsRequest {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="GetUnits", Namespace="http://his.cuahsi.org/his/1.1/ws/", Order=0)]
        public HydroDesktop.Data.ODMCVServiceClient.ServiceReference.ODMCV.GetUnitsRequestBody Body;
        
        public GetUnitsRequest() {
        }
        
        public GetUnitsRequest(HydroDesktop.Data.ODMCVServiceClient.ServiceReference.ODMCV.GetUnitsRequestBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute()]
    internal partial class GetUnitsRequestBody {
        
        public GetUnitsRequestBody() {
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    internal partial class GetUnitsResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="GetUnitsResponse", Namespace="http://his.cuahsi.org/his/1.1/ws/", Order=0)]
        public HydroDesktop.Data.ODMCVServiceClient.ServiceReference.ODMCV.GetUnitsResponseBody Body;
        
        public GetUnitsResponse() {
        }
        
        public GetUnitsResponse(HydroDesktop.Data.ODMCVServiceClient.ServiceReference.ODMCV.GetUnitsResponseBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://his.cuahsi.org/his/1.1/ws/")]
    internal partial class GetUnitsResponseBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public string GetUnitsResult;
        
        public GetUnitsResponseBody() {
        }
        
        public GetUnitsResponseBody(string GetUnitsResult) {
            this.GetUnitsResult = GetUnitsResult;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    internal partial class GetSpeciationCVRequest {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="GetSpeciationCV", Namespace="http://his.cuahsi.org/his/1.1/ws/", Order=0)]
        public HydroDesktop.Data.ODMCVServiceClient.ServiceReference.ODMCV.GetSpeciationCVRequestBody Body;
        
        public GetSpeciationCVRequest() {
        }
        
        public GetSpeciationCVRequest(HydroDesktop.Data.ODMCVServiceClient.ServiceReference.ODMCV.GetSpeciationCVRequestBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute()]
    internal partial class GetSpeciationCVRequestBody {
        
        public GetSpeciationCVRequestBody() {
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    internal partial class GetSpeciationCVResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="GetSpeciationCVResponse", Namespace="http://his.cuahsi.org/his/1.1/ws/", Order=0)]
        public HydroDesktop.Data.ODMCVServiceClient.ServiceReference.ODMCV.GetSpeciationCVResponseBody Body;
        
        public GetSpeciationCVResponse() {
        }
        
        public GetSpeciationCVResponse(HydroDesktop.Data.ODMCVServiceClient.ServiceReference.ODMCV.GetSpeciationCVResponseBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://his.cuahsi.org/his/1.1/ws/")]
    internal partial class GetSpeciationCVResponseBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public string GetSpeciationCVResult;
        
        public GetSpeciationCVResponseBody() {
        }
        
        public GetSpeciationCVResponseBody(string GetSpeciationCVResult) {
            this.GetSpeciationCVResult = GetSpeciationCVResult;
        }
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    internal interface ODMCVServiceSoapChannel : HydroDesktop.Data.ODMCVServiceClient.ServiceReference.ODMCV.ODMCVServiceSoap, System.ServiceModel.IClientChannel {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    internal partial class ODMCVServiceSoapClient : System.ServiceModel.ClientBase<HydroDesktop.Data.ODMCVServiceClient.ServiceReference.ODMCV.ODMCVServiceSoap>, HydroDesktop.Data.ODMCVServiceClient.ServiceReference.ODMCV.ODMCVServiceSoap {
        
        public ODMCVServiceSoapClient() {
        }
        
        public ODMCVServiceSoapClient(string endpointConfigurationName) : 
                base(endpointConfigurationName) {
        }
        
        public ODMCVServiceSoapClient(string endpointConfigurationName, string remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public ODMCVServiceSoapClient(string endpointConfigurationName, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public ODMCVServiceSoapClient(System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(binding, remoteAddress) {
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        HydroDesktop.Data.ODMCVServiceClient.ServiceReference.ODMCV.GetCensorCodeCVResponse HydroDesktop.Data.ODMCVServiceClient.ServiceReference.ODMCV.ODMCVServiceSoap.GetCensorCodeCV(HydroDesktop.Data.ODMCVServiceClient.ServiceReference.ODMCV.GetCensorCodeCVRequest request) {
            return base.Channel.GetCensorCodeCV(request);
        }
        
        public string GetCensorCodeCV() {
            HydroDesktop.Data.ODMCVServiceClient.ServiceReference.ODMCV.GetCensorCodeCVRequest inValue = new HydroDesktop.Data.ODMCVServiceClient.ServiceReference.ODMCV.GetCensorCodeCVRequest();
            inValue.Body = new HydroDesktop.Data.ODMCVServiceClient.ServiceReference.ODMCV.GetCensorCodeCVRequestBody();
            HydroDesktop.Data.ODMCVServiceClient.ServiceReference.ODMCV.GetCensorCodeCVResponse retVal = ((HydroDesktop.Data.ODMCVServiceClient.ServiceReference.ODMCV.ODMCVServiceSoap)(this)).GetCensorCodeCV(inValue);
            return retVal.Body.GetCensorCodeCVResult;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        HydroDesktop.Data.ODMCVServiceClient.ServiceReference.ODMCV.GetDataTypeCVResponse HydroDesktop.Data.ODMCVServiceClient.ServiceReference.ODMCV.ODMCVServiceSoap.GetDataTypeCV(HydroDesktop.Data.ODMCVServiceClient.ServiceReference.ODMCV.GetDataTypeCVRequest request) {
            return base.Channel.GetDataTypeCV(request);
        }
        
        public string GetDataTypeCV() {
            HydroDesktop.Data.ODMCVServiceClient.ServiceReference.ODMCV.GetDataTypeCVRequest inValue = new HydroDesktop.Data.ODMCVServiceClient.ServiceReference.ODMCV.GetDataTypeCVRequest();
            inValue.Body = new HydroDesktop.Data.ODMCVServiceClient.ServiceReference.ODMCV.GetDataTypeCVRequestBody();
            HydroDesktop.Data.ODMCVServiceClient.ServiceReference.ODMCV.GetDataTypeCVResponse retVal = ((HydroDesktop.Data.ODMCVServiceClient.ServiceReference.ODMCV.ODMCVServiceSoap)(this)).GetDataTypeCV(inValue);
            return retVal.Body.GetDataTypeCVResult;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        HydroDesktop.Data.ODMCVServiceClient.ServiceReference.ODMCV.GetGeneralCategoryCVResponse HydroDesktop.Data.ODMCVServiceClient.ServiceReference.ODMCV.ODMCVServiceSoap.GetGeneralCategoryCV(HydroDesktop.Data.ODMCVServiceClient.ServiceReference.ODMCV.GetGeneralCategoryCVRequest request) {
            return base.Channel.GetGeneralCategoryCV(request);
        }
        
        public string GetGeneralCategoryCV() {
            HydroDesktop.Data.ODMCVServiceClient.ServiceReference.ODMCV.GetGeneralCategoryCVRequest inValue = new HydroDesktop.Data.ODMCVServiceClient.ServiceReference.ODMCV.GetGeneralCategoryCVRequest();
            inValue.Body = new HydroDesktop.Data.ODMCVServiceClient.ServiceReference.ODMCV.GetGeneralCategoryCVRequestBody();
            HydroDesktop.Data.ODMCVServiceClient.ServiceReference.ODMCV.GetGeneralCategoryCVResponse retVal = ((HydroDesktop.Data.ODMCVServiceClient.ServiceReference.ODMCV.ODMCVServiceSoap)(this)).GetGeneralCategoryCV(inValue);
            return retVal.Body.GetGeneralCategoryCVResult;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        HydroDesktop.Data.ODMCVServiceClient.ServiceReference.ODMCV.GetSampleMediumCVResponse HydroDesktop.Data.ODMCVServiceClient.ServiceReference.ODMCV.ODMCVServiceSoap.GetSampleMediumCV(HydroDesktop.Data.ODMCVServiceClient.ServiceReference.ODMCV.GetSampleMediumCVRequest request) {
            return base.Channel.GetSampleMediumCV(request);
        }
        
        public string GetSampleMediumCV() {
            HydroDesktop.Data.ODMCVServiceClient.ServiceReference.ODMCV.GetSampleMediumCVRequest inValue = new HydroDesktop.Data.ODMCVServiceClient.ServiceReference.ODMCV.GetSampleMediumCVRequest();
            inValue.Body = new HydroDesktop.Data.ODMCVServiceClient.ServiceReference.ODMCV.GetSampleMediumCVRequestBody();
            HydroDesktop.Data.ODMCVServiceClient.ServiceReference.ODMCV.GetSampleMediumCVResponse retVal = ((HydroDesktop.Data.ODMCVServiceClient.ServiceReference.ODMCV.ODMCVServiceSoap)(this)).GetSampleMediumCV(inValue);
            return retVal.Body.GetSampleMediumCVResult;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        HydroDesktop.Data.ODMCVServiceClient.ServiceReference.ODMCV.GetSampleTypeCVResponse HydroDesktop.Data.ODMCVServiceClient.ServiceReference.ODMCV.ODMCVServiceSoap.GetSampleTypeCV(HydroDesktop.Data.ODMCVServiceClient.ServiceReference.ODMCV.GetSampleTypeCVRequest request) {
            return base.Channel.GetSampleTypeCV(request);
        }
        
        public string GetSampleTypeCV() {
            HydroDesktop.Data.ODMCVServiceClient.ServiceReference.ODMCV.GetSampleTypeCVRequest inValue = new HydroDesktop.Data.ODMCVServiceClient.ServiceReference.ODMCV.GetSampleTypeCVRequest();
            inValue.Body = new HydroDesktop.Data.ODMCVServiceClient.ServiceReference.ODMCV.GetSampleTypeCVRequestBody();
            HydroDesktop.Data.ODMCVServiceClient.ServiceReference.ODMCV.GetSampleTypeCVResponse retVal = ((HydroDesktop.Data.ODMCVServiceClient.ServiceReference.ODMCV.ODMCVServiceSoap)(this)).GetSampleTypeCV(inValue);
            return retVal.Body.GetSampleTypeCVResult;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        HydroDesktop.Data.ODMCVServiceClient.ServiceReference.ODMCV.GetTopicCategoryCVResponse HydroDesktop.Data.ODMCVServiceClient.ServiceReference.ODMCV.ODMCVServiceSoap.GetTopicCategoryCV(HydroDesktop.Data.ODMCVServiceClient.ServiceReference.ODMCV.GetTopicCategoryCVRequest request) {
            return base.Channel.GetTopicCategoryCV(request);
        }
        
        public string GetTopicCategoryCV() {
            HydroDesktop.Data.ODMCVServiceClient.ServiceReference.ODMCV.GetTopicCategoryCVRequest inValue = new HydroDesktop.Data.ODMCVServiceClient.ServiceReference.ODMCV.GetTopicCategoryCVRequest();
            inValue.Body = new HydroDesktop.Data.ODMCVServiceClient.ServiceReference.ODMCV.GetTopicCategoryCVRequestBody();
            HydroDesktop.Data.ODMCVServiceClient.ServiceReference.ODMCV.GetTopicCategoryCVResponse retVal = ((HydroDesktop.Data.ODMCVServiceClient.ServiceReference.ODMCV.ODMCVServiceSoap)(this)).GetTopicCategoryCV(inValue);
            return retVal.Body.GetTopicCategoryCVResult;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        HydroDesktop.Data.ODMCVServiceClient.ServiceReference.ODMCV.GetValueTypeCVResponse HydroDesktop.Data.ODMCVServiceClient.ServiceReference.ODMCV.ODMCVServiceSoap.GetValueTypeCV(HydroDesktop.Data.ODMCVServiceClient.ServiceReference.ODMCV.GetValueTypeCVRequest request) {
            return base.Channel.GetValueTypeCV(request);
        }
        
        public string GetValueTypeCV() {
            HydroDesktop.Data.ODMCVServiceClient.ServiceReference.ODMCV.GetValueTypeCVRequest inValue = new HydroDesktop.Data.ODMCVServiceClient.ServiceReference.ODMCV.GetValueTypeCVRequest();
            inValue.Body = new HydroDesktop.Data.ODMCVServiceClient.ServiceReference.ODMCV.GetValueTypeCVRequestBody();
            HydroDesktop.Data.ODMCVServiceClient.ServiceReference.ODMCV.GetValueTypeCVResponse retVal = ((HydroDesktop.Data.ODMCVServiceClient.ServiceReference.ODMCV.ODMCVServiceSoap)(this)).GetValueTypeCV(inValue);
            return retVal.Body.GetValueTypeCVResult;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        HydroDesktop.Data.ODMCVServiceClient.ServiceReference.ODMCV.GetVariableNameCVResponse HydroDesktop.Data.ODMCVServiceClient.ServiceReference.ODMCV.ODMCVServiceSoap.GetVariableNameCV(HydroDesktop.Data.ODMCVServiceClient.ServiceReference.ODMCV.GetVariableNameCVRequest request) {
            return base.Channel.GetVariableNameCV(request);
        }
        
        public string GetVariableNameCV() {
            HydroDesktop.Data.ODMCVServiceClient.ServiceReference.ODMCV.GetVariableNameCVRequest inValue = new HydroDesktop.Data.ODMCVServiceClient.ServiceReference.ODMCV.GetVariableNameCVRequest();
            inValue.Body = new HydroDesktop.Data.ODMCVServiceClient.ServiceReference.ODMCV.GetVariableNameCVRequestBody();
            HydroDesktop.Data.ODMCVServiceClient.ServiceReference.ODMCV.GetVariableNameCVResponse retVal = ((HydroDesktop.Data.ODMCVServiceClient.ServiceReference.ODMCV.ODMCVServiceSoap)(this)).GetVariableNameCV(inValue);
            return retVal.Body.GetVariableNameCVResult;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        HydroDesktop.Data.ODMCVServiceClient.ServiceReference.ODMCV.GetVerticalDatumCVResponse HydroDesktop.Data.ODMCVServiceClient.ServiceReference.ODMCV.ODMCVServiceSoap.GetVerticalDatumCV(HydroDesktop.Data.ODMCVServiceClient.ServiceReference.ODMCV.GetVerticalDatumCVRequest request) {
            return base.Channel.GetVerticalDatumCV(request);
        }
        
        public string GetVerticalDatumCV() {
            HydroDesktop.Data.ODMCVServiceClient.ServiceReference.ODMCV.GetVerticalDatumCVRequest inValue = new HydroDesktop.Data.ODMCVServiceClient.ServiceReference.ODMCV.GetVerticalDatumCVRequest();
            inValue.Body = new HydroDesktop.Data.ODMCVServiceClient.ServiceReference.ODMCV.GetVerticalDatumCVRequestBody();
            HydroDesktop.Data.ODMCVServiceClient.ServiceReference.ODMCV.GetVerticalDatumCVResponse retVal = ((HydroDesktop.Data.ODMCVServiceClient.ServiceReference.ODMCV.ODMCVServiceSoap)(this)).GetVerticalDatumCV(inValue);
            return retVal.Body.GetVerticalDatumCVResult;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        HydroDesktop.Data.ODMCVServiceClient.ServiceReference.ODMCV.GetSpatialReferencesResponse HydroDesktop.Data.ODMCVServiceClient.ServiceReference.ODMCV.ODMCVServiceSoap.GetSpatialReferences(HydroDesktop.Data.ODMCVServiceClient.ServiceReference.ODMCV.GetSpatialReferencesRequest request) {
            return base.Channel.GetSpatialReferences(request);
        }
        
        public string GetSpatialReferences() {
            HydroDesktop.Data.ODMCVServiceClient.ServiceReference.ODMCV.GetSpatialReferencesRequest inValue = new HydroDesktop.Data.ODMCVServiceClient.ServiceReference.ODMCV.GetSpatialReferencesRequest();
            inValue.Body = new HydroDesktop.Data.ODMCVServiceClient.ServiceReference.ODMCV.GetSpatialReferencesRequestBody();
            HydroDesktop.Data.ODMCVServiceClient.ServiceReference.ODMCV.GetSpatialReferencesResponse retVal = ((HydroDesktop.Data.ODMCVServiceClient.ServiceReference.ODMCV.ODMCVServiceSoap)(this)).GetSpatialReferences(inValue);
            return retVal.Body.GetSpatialReferencesResult;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        HydroDesktop.Data.ODMCVServiceClient.ServiceReference.ODMCV.GetUnitsResponse HydroDesktop.Data.ODMCVServiceClient.ServiceReference.ODMCV.ODMCVServiceSoap.GetUnits(HydroDesktop.Data.ODMCVServiceClient.ServiceReference.ODMCV.GetUnitsRequest request) {
            return base.Channel.GetUnits(request);
        }
        
        public string GetUnits() {
            HydroDesktop.Data.ODMCVServiceClient.ServiceReference.ODMCV.GetUnitsRequest inValue = new HydroDesktop.Data.ODMCVServiceClient.ServiceReference.ODMCV.GetUnitsRequest();
            inValue.Body = new HydroDesktop.Data.ODMCVServiceClient.ServiceReference.ODMCV.GetUnitsRequestBody();
            HydroDesktop.Data.ODMCVServiceClient.ServiceReference.ODMCV.GetUnitsResponse retVal = ((HydroDesktop.Data.ODMCVServiceClient.ServiceReference.ODMCV.ODMCVServiceSoap)(this)).GetUnits(inValue);
            return retVal.Body.GetUnitsResult;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        HydroDesktop.Data.ODMCVServiceClient.ServiceReference.ODMCV.GetSpeciationCVResponse HydroDesktop.Data.ODMCVServiceClient.ServiceReference.ODMCV.ODMCVServiceSoap.GetSpeciationCV(HydroDesktop.Data.ODMCVServiceClient.ServiceReference.ODMCV.GetSpeciationCVRequest request) {
            return base.Channel.GetSpeciationCV(request);
        }
        
        public string GetSpeciationCV() {
            HydroDesktop.Data.ODMCVServiceClient.ServiceReference.ODMCV.GetSpeciationCVRequest inValue = new HydroDesktop.Data.ODMCVServiceClient.ServiceReference.ODMCV.GetSpeciationCVRequest();
            inValue.Body = new HydroDesktop.Data.ODMCVServiceClient.ServiceReference.ODMCV.GetSpeciationCVRequestBody();
            HydroDesktop.Data.ODMCVServiceClient.ServiceReference.ODMCV.GetSpeciationCVResponse retVal = ((HydroDesktop.Data.ODMCVServiceClient.ServiceReference.ODMCV.ODMCVServiceSoap)(this)).GetSpeciationCV(inValue);
            return retVal.Body.GetSpeciationCVResult;
        }
    }
}
