//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.239
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace FacetedSearch3.CUAHSIFacetedSearch {
    using System.Runtime.Serialization;
    using System;
    
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="OntologyElement", Namespace="http://schemas.datacontract.org/2004/07/MultiFacetedHIS")]
    [System.SerializableAttribute()]
    public partial class OntologyElement : object, System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged {
        
        [System.NonSerializedAttribute()]
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private bool IsLeafField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private bool IsRootField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private bool IsSearchableField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private int LayerField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private int QuerystructuretblField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string SynonymField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private int cConceptIDField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string cConceptNameField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private int cParentIDField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string itsJoinPropertyField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private double latitudeField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private double longitudeField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string myJoinPropertyField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string mySearchPropertyField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private int seriesCatalogDistanceField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private int tblJoinsToField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string tblNameField;
        
        [global::System.ComponentModel.BrowsableAttribute(false)]
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData {
            get {
                return this.extensionDataField;
            }
            set {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public bool IsLeaf {
            get {
                return this.IsLeafField;
            }
            set {
                if ((this.IsLeafField.Equals(value) != true)) {
                    this.IsLeafField = value;
                    this.RaisePropertyChanged("IsLeaf");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public bool IsRoot {
            get {
                return this.IsRootField;
            }
            set {
                if ((this.IsRootField.Equals(value) != true)) {
                    this.IsRootField = value;
                    this.RaisePropertyChanged("IsRoot");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public bool IsSearchable {
            get {
                return this.IsSearchableField;
            }
            set {
                if ((this.IsSearchableField.Equals(value) != true)) {
                    this.IsSearchableField = value;
                    this.RaisePropertyChanged("IsSearchable");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int Layer {
            get {
                return this.LayerField;
            }
            set {
                if ((this.LayerField.Equals(value) != true)) {
                    this.LayerField = value;
                    this.RaisePropertyChanged("Layer");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int Querystructuretbl {
            get {
                return this.QuerystructuretblField;
            }
            set {
                if ((this.QuerystructuretblField.Equals(value) != true)) {
                    this.QuerystructuretblField = value;
                    this.RaisePropertyChanged("Querystructuretbl");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Synonym {
            get {
                return this.SynonymField;
            }
            set {
                if ((object.ReferenceEquals(this.SynonymField, value) != true)) {
                    this.SynonymField = value;
                    this.RaisePropertyChanged("Synonym");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int cConceptID {
            get {
                return this.cConceptIDField;
            }
            set {
                if ((this.cConceptIDField.Equals(value) != true)) {
                    this.cConceptIDField = value;
                    this.RaisePropertyChanged("cConceptID");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string cConceptName {
            get {
                return this.cConceptNameField;
            }
            set {
                if ((object.ReferenceEquals(this.cConceptNameField, value) != true)) {
                    this.cConceptNameField = value;
                    this.RaisePropertyChanged("cConceptName");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int cParentID {
            get {
                return this.cParentIDField;
            }
            set {
                if ((this.cParentIDField.Equals(value) != true)) {
                    this.cParentIDField = value;
                    this.RaisePropertyChanged("cParentID");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string itsJoinProperty {
            get {
                return this.itsJoinPropertyField;
            }
            set {
                if ((object.ReferenceEquals(this.itsJoinPropertyField, value) != true)) {
                    this.itsJoinPropertyField = value;
                    this.RaisePropertyChanged("itsJoinProperty");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public double latitude {
            get {
                return this.latitudeField;
            }
            set {
                if ((this.latitudeField.Equals(value) != true)) {
                    this.latitudeField = value;
                    this.RaisePropertyChanged("latitude");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public double longitude {
            get {
                return this.longitudeField;
            }
            set {
                if ((this.longitudeField.Equals(value) != true)) {
                    this.longitudeField = value;
                    this.RaisePropertyChanged("longitude");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string myJoinProperty {
            get {
                return this.myJoinPropertyField;
            }
            set {
                if ((object.ReferenceEquals(this.myJoinPropertyField, value) != true)) {
                    this.myJoinPropertyField = value;
                    this.RaisePropertyChanged("myJoinProperty");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string mySearchProperty {
            get {
                return this.mySearchPropertyField;
            }
            set {
                if ((object.ReferenceEquals(this.mySearchPropertyField, value) != true)) {
                    this.mySearchPropertyField = value;
                    this.RaisePropertyChanged("mySearchProperty");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int seriesCatalogDistance {
            get {
                return this.seriesCatalogDistanceField;
            }
            set {
                if ((this.seriesCatalogDistanceField.Equals(value) != true)) {
                    this.seriesCatalogDistanceField = value;
                    this.RaisePropertyChanged("seriesCatalogDistance");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int tblJoinsTo {
            get {
                return this.tblJoinsToField;
            }
            set {
                if ((this.tblJoinsToField.Equals(value) != true)) {
                    this.tblJoinsToField = value;
                    this.RaisePropertyChanged("tblJoinsTo");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string tblName {
            get {
                return this.tblNameField;
            }
            set {
                if ((object.ReferenceEquals(this.tblNameField, value) != true)) {
                    this.tblNameField = value;
                    this.RaisePropertyChanged("tblName");
                }
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="OntologyEnvelope", Namespace="http://schemas.datacontract.org/2004/07/MultiFacetedHIS")]
    [System.SerializableAttribute()]
    public partial class OntologyEnvelope : object, System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged {
        
        [System.NonSerializedAttribute()]
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private FacetedSearch3.CUAHSIFacetedSearch.OntologyElement[] OntologyElementsField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private FacetedSearch3.CUAHSIFacetedSearch.SiteData[] SitesField;
        
        [global::System.ComponentModel.BrowsableAttribute(false)]
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData {
            get {
                return this.extensionDataField;
            }
            set {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public FacetedSearch3.CUAHSIFacetedSearch.OntologyElement[] OntologyElements {
            get {
                return this.OntologyElementsField;
            }
            set {
                if ((object.ReferenceEquals(this.OntologyElementsField, value) != true)) {
                    this.OntologyElementsField = value;
                    this.RaisePropertyChanged("OntologyElements");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public FacetedSearch3.CUAHSIFacetedSearch.SiteData[] Sites {
            get {
                return this.SitesField;
            }
            set {
                if ((object.ReferenceEquals(this.SitesField, value) != true)) {
                    this.SitesField = value;
                    this.RaisePropertyChanged("Sites");
                }
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="SiteData", Namespace="http://schemas.datacontract.org/2004/07/MultiFacetedHIS")]
    [System.SerializableAttribute()]
    public partial class SiteData : object, System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged {
        
        [System.NonSerializedAttribute()]
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private int SiteIDField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private double latitudeField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private double longitudeField;
        
        [global::System.ComponentModel.BrowsableAttribute(false)]
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData {
            get {
                return this.extensionDataField;
            }
            set {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int SiteID {
            get {
                return this.SiteIDField;
            }
            set {
                if ((this.SiteIDField.Equals(value) != true)) {
                    this.SiteIDField = value;
                    this.RaisePropertyChanged("SiteID");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public double latitude {
            get {
                return this.latitudeField;
            }
            set {
                if ((this.latitudeField.Equals(value) != true)) {
                    this.latitudeField = value;
                    this.RaisePropertyChanged("latitude");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public double longitude {
            get {
                return this.longitudeField;
            }
            set {
                if ((this.longitudeField.Equals(value) != true)) {
                    this.longitudeField = value;
                    this.RaisePropertyChanged("longitude");
                }
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="SeriesCatalogRecord", Namespace="http://schemas.datacontract.org/2004/07/MultiFacetedHIS")]
    [System.SerializableAttribute()]
    public partial class SeriesCatalogRecord : object, System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged {
        
        [System.NonSerializedAttribute()]
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private System.DateTime EndDateField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private double LatitudeField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private double LongitudeField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private int SeriesIDField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string ServCodeField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string ServURLField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string SiteCodeField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private int SiteIDField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string SiteNameField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private System.DateTime StartDateField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private int ValueCountField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string VarCodeField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string VariableNameField;
        
        [global::System.ComponentModel.BrowsableAttribute(false)]
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData {
            get {
                return this.extensionDataField;
            }
            set {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public System.DateTime EndDate {
            get {
                return this.EndDateField;
            }
            set {
                if ((this.EndDateField.Equals(value) != true)) {
                    this.EndDateField = value;
                    this.RaisePropertyChanged("EndDate");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public double Latitude {
            get {
                return this.LatitudeField;
            }
            set {
                if ((this.LatitudeField.Equals(value) != true)) {
                    this.LatitudeField = value;
                    this.RaisePropertyChanged("Latitude");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public double Longitude {
            get {
                return this.LongitudeField;
            }
            set {
                if ((this.LongitudeField.Equals(value) != true)) {
                    this.LongitudeField = value;
                    this.RaisePropertyChanged("Longitude");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int SeriesID {
            get {
                return this.SeriesIDField;
            }
            set {
                if ((this.SeriesIDField.Equals(value) != true)) {
                    this.SeriesIDField = value;
                    this.RaisePropertyChanged("SeriesID");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string ServCode {
            get {
                return this.ServCodeField;
            }
            set {
                if ((object.ReferenceEquals(this.ServCodeField, value) != true)) {
                    this.ServCodeField = value;
                    this.RaisePropertyChanged("ServCode");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string ServURL {
            get {
                return this.ServURLField;
            }
            set {
                if ((object.ReferenceEquals(this.ServURLField, value) != true)) {
                    this.ServURLField = value;
                    this.RaisePropertyChanged("ServURL");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string SiteCode {
            get {
                return this.SiteCodeField;
            }
            set {
                if ((object.ReferenceEquals(this.SiteCodeField, value) != true)) {
                    this.SiteCodeField = value;
                    this.RaisePropertyChanged("SiteCode");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int SiteID {
            get {
                return this.SiteIDField;
            }
            set {
                if ((this.SiteIDField.Equals(value) != true)) {
                    this.SiteIDField = value;
                    this.RaisePropertyChanged("SiteID");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string SiteName {
            get {
                return this.SiteNameField;
            }
            set {
                if ((object.ReferenceEquals(this.SiteNameField, value) != true)) {
                    this.SiteNameField = value;
                    this.RaisePropertyChanged("SiteName");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public System.DateTime StartDate {
            get {
                return this.StartDateField;
            }
            set {
                if ((this.StartDateField.Equals(value) != true)) {
                    this.StartDateField = value;
                    this.RaisePropertyChanged("StartDate");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int ValueCount {
            get {
                return this.ValueCountField;
            }
            set {
                if ((this.ValueCountField.Equals(value) != true)) {
                    this.ValueCountField = value;
                    this.RaisePropertyChanged("ValueCount");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string VarCode {
            get {
                return this.VarCodeField;
            }
            set {
                if ((object.ReferenceEquals(this.VarCodeField, value) != true)) {
                    this.VarCodeField = value;
                    this.RaisePropertyChanged("VarCode");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string VariableName {
            get {
                return this.VariableNameField;
            }
            set {
                if ((object.ReferenceEquals(this.VariableNameField, value) != true)) {
                    this.VariableNameField = value;
                    this.RaisePropertyChanged("VariableName");
                }
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="SelectionDensityReport", Namespace="http://schemas.datacontract.org/2004/07/MultiFacetedHIS")]
    [System.SerializableAttribute()]
    public partial class SelectionDensityReport : object, System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged {
        
        [System.NonSerializedAttribute()]
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private System.DateTime BeginTimeField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private int ChoiceCountField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private System.DateTime EndTimeField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private System.Collections.Generic.Dictionary<string, FacetedSearch3.CUAHSIFacetedSearch.OntologyElement> FacetSelectionField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private FacetedSearch3.CUAHSIFacetedSearch.OntologyElement[] FacetSelectionRootField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private int Layer1OptionsField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private int Layer2OptionsField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private int Layer3OptionsField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private int Layer4OptionsField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private int Layer5OptionsField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private int Layer6OptionsField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private int Layer7OptionsField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private int Layer8OptionsField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private double MaxXField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private double MaxYField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private double MinXField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private double MinYField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private int OntologyCountField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private FacetedSearch3.CUAHSIFacetedSearch.OntologyElement[] RemainingOntologyElementsField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private int RootLayerOptionsField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private int SeriesCountField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private int[] TopConstraintDimensionsField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private System.Collections.Generic.Dictionary<string, FacetedSearch3.CUAHSIFacetedSearch.OntologyElement> TopConstraintSelectionField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private long ValueCountField;
        
        [global::System.ComponentModel.BrowsableAttribute(false)]
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData {
            get {
                return this.extensionDataField;
            }
            set {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public System.DateTime BeginTime {
            get {
                return this.BeginTimeField;
            }
            set {
                if ((this.BeginTimeField.Equals(value) != true)) {
                    this.BeginTimeField = value;
                    this.RaisePropertyChanged("BeginTime");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int ChoiceCount {
            get {
                return this.ChoiceCountField;
            }
            set {
                if ((this.ChoiceCountField.Equals(value) != true)) {
                    this.ChoiceCountField = value;
                    this.RaisePropertyChanged("ChoiceCount");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public System.DateTime EndTime {
            get {
                return this.EndTimeField;
            }
            set {
                if ((this.EndTimeField.Equals(value) != true)) {
                    this.EndTimeField = value;
                    this.RaisePropertyChanged("EndTime");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public System.Collections.Generic.Dictionary<string, FacetedSearch3.CUAHSIFacetedSearch.OntologyElement> FacetSelection {
            get {
                return this.FacetSelectionField;
            }
            set {
                if ((object.ReferenceEquals(this.FacetSelectionField, value) != true)) {
                    this.FacetSelectionField = value;
                    this.RaisePropertyChanged("FacetSelection");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public FacetedSearch3.CUAHSIFacetedSearch.OntologyElement[] FacetSelectionRoot {
            get {
                return this.FacetSelectionRootField;
            }
            set {
                if ((object.ReferenceEquals(this.FacetSelectionRootField, value) != true)) {
                    this.FacetSelectionRootField = value;
                    this.RaisePropertyChanged("FacetSelectionRoot");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int Layer1Options {
            get {
                return this.Layer1OptionsField;
            }
            set {
                if ((this.Layer1OptionsField.Equals(value) != true)) {
                    this.Layer1OptionsField = value;
                    this.RaisePropertyChanged("Layer1Options");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int Layer2Options {
            get {
                return this.Layer2OptionsField;
            }
            set {
                if ((this.Layer2OptionsField.Equals(value) != true)) {
                    this.Layer2OptionsField = value;
                    this.RaisePropertyChanged("Layer2Options");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int Layer3Options {
            get {
                return this.Layer3OptionsField;
            }
            set {
                if ((this.Layer3OptionsField.Equals(value) != true)) {
                    this.Layer3OptionsField = value;
                    this.RaisePropertyChanged("Layer3Options");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int Layer4Options {
            get {
                return this.Layer4OptionsField;
            }
            set {
                if ((this.Layer4OptionsField.Equals(value) != true)) {
                    this.Layer4OptionsField = value;
                    this.RaisePropertyChanged("Layer4Options");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int Layer5Options {
            get {
                return this.Layer5OptionsField;
            }
            set {
                if ((this.Layer5OptionsField.Equals(value) != true)) {
                    this.Layer5OptionsField = value;
                    this.RaisePropertyChanged("Layer5Options");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int Layer6Options {
            get {
                return this.Layer6OptionsField;
            }
            set {
                if ((this.Layer6OptionsField.Equals(value) != true)) {
                    this.Layer6OptionsField = value;
                    this.RaisePropertyChanged("Layer6Options");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int Layer7Options {
            get {
                return this.Layer7OptionsField;
            }
            set {
                if ((this.Layer7OptionsField.Equals(value) != true)) {
                    this.Layer7OptionsField = value;
                    this.RaisePropertyChanged("Layer7Options");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int Layer8Options {
            get {
                return this.Layer8OptionsField;
            }
            set {
                if ((this.Layer8OptionsField.Equals(value) != true)) {
                    this.Layer8OptionsField = value;
                    this.RaisePropertyChanged("Layer8Options");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public double MaxX {
            get {
                return this.MaxXField;
            }
            set {
                if ((this.MaxXField.Equals(value) != true)) {
                    this.MaxXField = value;
                    this.RaisePropertyChanged("MaxX");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public double MaxY {
            get {
                return this.MaxYField;
            }
            set {
                if ((this.MaxYField.Equals(value) != true)) {
                    this.MaxYField = value;
                    this.RaisePropertyChanged("MaxY");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public double MinX {
            get {
                return this.MinXField;
            }
            set {
                if ((this.MinXField.Equals(value) != true)) {
                    this.MinXField = value;
                    this.RaisePropertyChanged("MinX");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public double MinY {
            get {
                return this.MinYField;
            }
            set {
                if ((this.MinYField.Equals(value) != true)) {
                    this.MinYField = value;
                    this.RaisePropertyChanged("MinY");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int OntologyCount {
            get {
                return this.OntologyCountField;
            }
            set {
                if ((this.OntologyCountField.Equals(value) != true)) {
                    this.OntologyCountField = value;
                    this.RaisePropertyChanged("OntologyCount");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public FacetedSearch3.CUAHSIFacetedSearch.OntologyElement[] RemainingOntologyElements {
            get {
                return this.RemainingOntologyElementsField;
            }
            set {
                if ((object.ReferenceEquals(this.RemainingOntologyElementsField, value) != true)) {
                    this.RemainingOntologyElementsField = value;
                    this.RaisePropertyChanged("RemainingOntologyElements");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int RootLayerOptions {
            get {
                return this.RootLayerOptionsField;
            }
            set {
                if ((this.RootLayerOptionsField.Equals(value) != true)) {
                    this.RootLayerOptionsField = value;
                    this.RaisePropertyChanged("RootLayerOptions");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int SeriesCount {
            get {
                return this.SeriesCountField;
            }
            set {
                if ((this.SeriesCountField.Equals(value) != true)) {
                    this.SeriesCountField = value;
                    this.RaisePropertyChanged("SeriesCount");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int[] TopConstraintDimensions {
            get {
                return this.TopConstraintDimensionsField;
            }
            set {
                if ((object.ReferenceEquals(this.TopConstraintDimensionsField, value) != true)) {
                    this.TopConstraintDimensionsField = value;
                    this.RaisePropertyChanged("TopConstraintDimensions");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public System.Collections.Generic.Dictionary<string, FacetedSearch3.CUAHSIFacetedSearch.OntologyElement> TopConstraintSelection {
            get {
                return this.TopConstraintSelectionField;
            }
            set {
                if ((object.ReferenceEquals(this.TopConstraintSelectionField, value) != true)) {
                    this.TopConstraintSelectionField = value;
                    this.RaisePropertyChanged("TopConstraintSelection");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public long ValueCount {
            get {
                return this.ValueCountField;
            }
            set {
                if ((this.ValueCountField.Equals(value) != true)) {
                    this.ValueCountField = value;
                    this.RaisePropertyChanged("ValueCount");
                }
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.ServiceContractAttribute(ConfigurationName="CUAHSIFacetedSearch.MultiFacetedHISSvc")]
    public interface MultiFacetedHISSvc {
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/MultiFacetedHISSvc/GetOntologyElements", ReplyAction="http://tempuri.org/MultiFacetedHISSvc/GetOntologyElementsResponse")]
        FacetedSearch3.CUAHSIFacetedSearch.OntologyElement[] GetOntologyElements();
        
        [System.ServiceModel.OperationContractAttribute(AsyncPattern=true, Action="http://tempuri.org/MultiFacetedHISSvc/GetOntologyElements", ReplyAction="http://tempuri.org/MultiFacetedHISSvc/GetOntologyElementsResponse")]
        System.IAsyncResult BeginGetOntologyElements(System.AsyncCallback callback, object asyncState);
        
        FacetedSearch3.CUAHSIFacetedSearch.OntologyElement[] EndGetOntologyElements(System.IAsyncResult result);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/MultiFacetedHISSvc/GetOntologyElementsGivenConstraints", ReplyAction="http://tempuri.org/MultiFacetedHISSvc/GetOntologyElementsGivenConstraintsResponse" +
            "")]
        FacetedSearch3.CUAHSIFacetedSearch.OntologyEnvelope GetOntologyElementsGivenConstraints(FacetedSearch3.CUAHSIFacetedSearch.OntologyElement[] Selections, System.DateTime BeginTime, System.DateTime EndTime, double MinY, double MaxY, double MinX, double MaxX, bool IncludeSpatialResults);
        
        [System.ServiceModel.OperationContractAttribute(AsyncPattern=true, Action="http://tempuri.org/MultiFacetedHISSvc/GetOntologyElementsGivenConstraints", ReplyAction="http://tempuri.org/MultiFacetedHISSvc/GetOntologyElementsGivenConstraintsResponse" +
            "")]
        System.IAsyncResult BeginGetOntologyElementsGivenConstraints(FacetedSearch3.CUAHSIFacetedSearch.OntologyElement[] Selections, System.DateTime BeginTime, System.DateTime EndTime, double MinY, double MaxY, double MinX, double MaxX, bool IncludeSpatialResults, System.AsyncCallback callback, object asyncState);
        
        FacetedSearch3.CUAHSIFacetedSearch.OntologyEnvelope EndGetOntologyElementsGivenConstraints(System.IAsyncResult result);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/MultiFacetedHISSvc/GetSeriesGivenConstraints", ReplyAction="http://tempuri.org/MultiFacetedHISSvc/GetSeriesGivenConstraintsResponse")]
        FacetedSearch3.CUAHSIFacetedSearch.SeriesCatalogRecord[] GetSeriesGivenConstraints(FacetedSearch3.CUAHSIFacetedSearch.OntologyElement[] Selections, System.DateTime BeginTime, System.DateTime EndTime, double MinY, double MaxY, double MinX, double MaxX);
        
        [System.ServiceModel.OperationContractAttribute(AsyncPattern=true, Action="http://tempuri.org/MultiFacetedHISSvc/GetSeriesGivenConstraints", ReplyAction="http://tempuri.org/MultiFacetedHISSvc/GetSeriesGivenConstraintsResponse")]
        System.IAsyncResult BeginGetSeriesGivenConstraints(FacetedSearch3.CUAHSIFacetedSearch.OntologyElement[] Selections, System.DateTime BeginTime, System.DateTime EndTime, double MinY, double MaxY, double MinX, double MaxX, System.AsyncCallback callback, object asyncState);
        
        FacetedSearch3.CUAHSIFacetedSearch.SeriesCatalogRecord[] EndGetSeriesGivenConstraints(System.IAsyncResult result);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/MultiFacetedHISSvc/GetOntologyElementsDataDensities", ReplyAction="http://tempuri.org/MultiFacetedHISSvc/GetOntologyElementsDataDensitiesResponse")]
        FacetedSearch3.CUAHSIFacetedSearch.SelectionDensityReport GetOntologyElementsDataDensities(System.Collections.Generic.Dictionary<string, FacetedSearch3.CUAHSIFacetedSearch.OntologyElement> Selections, System.DateTime BeginTime, System.DateTime EndTime, double MinY, double MaxY, double MinX, double MaxX, bool IncludeSpatialResults);
        
        [System.ServiceModel.OperationContractAttribute(AsyncPattern=true, Action="http://tempuri.org/MultiFacetedHISSvc/GetOntologyElementsDataDensities", ReplyAction="http://tempuri.org/MultiFacetedHISSvc/GetOntologyElementsDataDensitiesResponse")]
        System.IAsyncResult BeginGetOntologyElementsDataDensities(System.Collections.Generic.Dictionary<string, FacetedSearch3.CUAHSIFacetedSearch.OntologyElement> Selections, System.DateTime BeginTime, System.DateTime EndTime, double MinY, double MaxY, double MinX, double MaxX, bool IncludeSpatialResults, System.AsyncCallback callback, object asyncState);
        
        FacetedSearch3.CUAHSIFacetedSearch.SelectionDensityReport EndGetOntologyElementsDataDensities(System.IAsyncResult result);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/MultiFacetedHISSvc/GetSQLOfNextQuery", ReplyAction="http://tempuri.org/MultiFacetedHISSvc/GetSQLOfNextQueryResponse")]
        string GetSQLOfNextQuery(FacetedSearch3.CUAHSIFacetedSearch.OntologyElement[] Selections, System.DateTime BeginTime, System.DateTime EndTime, double MinY, double MaxY, double MinX, double MaxX, bool IncludeSpatialResults);
        
        [System.ServiceModel.OperationContractAttribute(AsyncPattern=true, Action="http://tempuri.org/MultiFacetedHISSvc/GetSQLOfNextQuery", ReplyAction="http://tempuri.org/MultiFacetedHISSvc/GetSQLOfNextQueryResponse")]
        System.IAsyncResult BeginGetSQLOfNextQuery(FacetedSearch3.CUAHSIFacetedSearch.OntologyElement[] Selections, System.DateTime BeginTime, System.DateTime EndTime, double MinY, double MaxY, double MinX, double MaxX, bool IncludeSpatialResults, System.AsyncCallback callback, object asyncState);
        
        string EndGetSQLOfNextQuery(System.IAsyncResult result);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/MultiFacetedHISSvc/GetSQLOfSearchQuery", ReplyAction="http://tempuri.org/MultiFacetedHISSvc/GetSQLOfSearchQueryResponse")]
        string GetSQLOfSearchQuery(FacetedSearch3.CUAHSIFacetedSearch.OntologyElement[] Selections, System.DateTime BeginTime, System.DateTime EndTime, double MinY, double MaxY, double MinX, double MaxX, bool IncludeSpatialResults);
        
        [System.ServiceModel.OperationContractAttribute(AsyncPattern=true, Action="http://tempuri.org/MultiFacetedHISSvc/GetSQLOfSearchQuery", ReplyAction="http://tempuri.org/MultiFacetedHISSvc/GetSQLOfSearchQueryResponse")]
        System.IAsyncResult BeginGetSQLOfSearchQuery(FacetedSearch3.CUAHSIFacetedSearch.OntologyElement[] Selections, System.DateTime BeginTime, System.DateTime EndTime, double MinY, double MaxY, double MinX, double MaxX, bool IncludeSpatialResults, System.AsyncCallback callback, object asyncState);
        
        string EndGetSQLOfSearchQuery(System.IAsyncResult result);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/MultiFacetedHISSvc/GetSQLOfNextDensityQuery", ReplyAction="http://tempuri.org/MultiFacetedHISSvc/GetSQLOfNextDensityQueryResponse")]
        string GetSQLOfNextDensityQuery(FacetedSearch3.CUAHSIFacetedSearch.OntologyElement[] Selections, System.DateTime BeginTime, System.DateTime EndTime, double MinY, double MaxY, double MinX, double MaxX, bool IncludeSpatialResults);
        
        [System.ServiceModel.OperationContractAttribute(AsyncPattern=true, Action="http://tempuri.org/MultiFacetedHISSvc/GetSQLOfNextDensityQuery", ReplyAction="http://tempuri.org/MultiFacetedHISSvc/GetSQLOfNextDensityQueryResponse")]
        System.IAsyncResult BeginGetSQLOfNextDensityQuery(FacetedSearch3.CUAHSIFacetedSearch.OntologyElement[] Selections, System.DateTime BeginTime, System.DateTime EndTime, double MinY, double MaxY, double MinX, double MaxX, bool IncludeSpatialResults, System.AsyncCallback callback, object asyncState);
        
        string EndGetSQLOfNextDensityQuery(System.IAsyncResult result);
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public interface MultiFacetedHISSvcChannel : FacetedSearch3.CUAHSIFacetedSearch.MultiFacetedHISSvc, System.ServiceModel.IClientChannel {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public partial class GetOntologyElementsCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        public GetOntologyElementsCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        public FacetedSearch3.CUAHSIFacetedSearch.OntologyElement[] Result {
            get {
                base.RaiseExceptionIfNecessary();
                return ((FacetedSearch3.CUAHSIFacetedSearch.OntologyElement[])(this.results[0]));
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public partial class GetOntologyElementsGivenConstraintsCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        public GetOntologyElementsGivenConstraintsCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        public FacetedSearch3.CUAHSIFacetedSearch.OntologyEnvelope Result {
            get {
                base.RaiseExceptionIfNecessary();
                return ((FacetedSearch3.CUAHSIFacetedSearch.OntologyEnvelope)(this.results[0]));
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public partial class GetSeriesGivenConstraintsCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        public GetSeriesGivenConstraintsCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        public FacetedSearch3.CUAHSIFacetedSearch.SeriesCatalogRecord[] Result {
            get {
                base.RaiseExceptionIfNecessary();
                return ((FacetedSearch3.CUAHSIFacetedSearch.SeriesCatalogRecord[])(this.results[0]));
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public partial class GetOntologyElementsDataDensitiesCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        public GetOntologyElementsDataDensitiesCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        public FacetedSearch3.CUAHSIFacetedSearch.SelectionDensityReport Result {
            get {
                base.RaiseExceptionIfNecessary();
                return ((FacetedSearch3.CUAHSIFacetedSearch.SelectionDensityReport)(this.results[0]));
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public partial class GetSQLOfNextQueryCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        public GetSQLOfNextQueryCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        public string Result {
            get {
                base.RaiseExceptionIfNecessary();
                return ((string)(this.results[0]));
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public partial class GetSQLOfSearchQueryCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        public GetSQLOfSearchQueryCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        public string Result {
            get {
                base.RaiseExceptionIfNecessary();
                return ((string)(this.results[0]));
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public partial class GetSQLOfNextDensityQueryCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        public GetSQLOfNextDensityQueryCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        public string Result {
            get {
                base.RaiseExceptionIfNecessary();
                return ((string)(this.results[0]));
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public partial class MultiFacetedHISSvcClient : System.ServiceModel.ClientBase<FacetedSearch3.CUAHSIFacetedSearch.MultiFacetedHISSvc>, FacetedSearch3.CUAHSIFacetedSearch.MultiFacetedHISSvc {
        
        private BeginOperationDelegate onBeginGetOntologyElementsDelegate;
        
        private EndOperationDelegate onEndGetOntologyElementsDelegate;
        
        private System.Threading.SendOrPostCallback onGetOntologyElementsCompletedDelegate;
        
        private BeginOperationDelegate onBeginGetOntologyElementsGivenConstraintsDelegate;
        
        private EndOperationDelegate onEndGetOntologyElementsGivenConstraintsDelegate;
        
        private System.Threading.SendOrPostCallback onGetOntologyElementsGivenConstraintsCompletedDelegate;
        
        private BeginOperationDelegate onBeginGetSeriesGivenConstraintsDelegate;
        
        private EndOperationDelegate onEndGetSeriesGivenConstraintsDelegate;
        
        private System.Threading.SendOrPostCallback onGetSeriesGivenConstraintsCompletedDelegate;
        
        private BeginOperationDelegate onBeginGetOntologyElementsDataDensitiesDelegate;
        
        private EndOperationDelegate onEndGetOntologyElementsDataDensitiesDelegate;
        
        private System.Threading.SendOrPostCallback onGetOntologyElementsDataDensitiesCompletedDelegate;
        
        private BeginOperationDelegate onBeginGetSQLOfNextQueryDelegate;
        
        private EndOperationDelegate onEndGetSQLOfNextQueryDelegate;
        
        private System.Threading.SendOrPostCallback onGetSQLOfNextQueryCompletedDelegate;
        
        private BeginOperationDelegate onBeginGetSQLOfSearchQueryDelegate;
        
        private EndOperationDelegate onEndGetSQLOfSearchQueryDelegate;
        
        private System.Threading.SendOrPostCallback onGetSQLOfSearchQueryCompletedDelegate;
        
        private BeginOperationDelegate onBeginGetSQLOfNextDensityQueryDelegate;
        
        private EndOperationDelegate onEndGetSQLOfNextDensityQueryDelegate;
        
        private System.Threading.SendOrPostCallback onGetSQLOfNextDensityQueryCompletedDelegate;
        
        public MultiFacetedHISSvcClient() {
        }
        
        public MultiFacetedHISSvcClient(string endpointConfigurationName) : 
                base(endpointConfigurationName) {
        }
        
        public MultiFacetedHISSvcClient(string endpointConfigurationName, string remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public MultiFacetedHISSvcClient(string endpointConfigurationName, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public MultiFacetedHISSvcClient(System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(binding, remoteAddress) {
        }
        
        public event System.EventHandler<GetOntologyElementsCompletedEventArgs> GetOntologyElementsCompleted;
        
        public event System.EventHandler<GetOntologyElementsGivenConstraintsCompletedEventArgs> GetOntologyElementsGivenConstraintsCompleted;
        
        public event System.EventHandler<GetSeriesGivenConstraintsCompletedEventArgs> GetSeriesGivenConstraintsCompleted;
        
        public event System.EventHandler<GetOntologyElementsDataDensitiesCompletedEventArgs> GetOntologyElementsDataDensitiesCompleted;
        
        public event System.EventHandler<GetSQLOfNextQueryCompletedEventArgs> GetSQLOfNextQueryCompleted;
        
        public event System.EventHandler<GetSQLOfSearchQueryCompletedEventArgs> GetSQLOfSearchQueryCompleted;
        
        public event System.EventHandler<GetSQLOfNextDensityQueryCompletedEventArgs> GetSQLOfNextDensityQueryCompleted;
        
        public FacetedSearch3.CUAHSIFacetedSearch.OntologyElement[] GetOntologyElements() {
            return base.Channel.GetOntologyElements();
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        public System.IAsyncResult BeginGetOntologyElements(System.AsyncCallback callback, object asyncState) {
            return base.Channel.BeginGetOntologyElements(callback, asyncState);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        public FacetedSearch3.CUAHSIFacetedSearch.OntologyElement[] EndGetOntologyElements(System.IAsyncResult result) {
            return base.Channel.EndGetOntologyElements(result);
        }
        
        private System.IAsyncResult OnBeginGetOntologyElements(object[] inValues, System.AsyncCallback callback, object asyncState) {
            return this.BeginGetOntologyElements(callback, asyncState);
        }
        
        private object[] OnEndGetOntologyElements(System.IAsyncResult result) {
            FacetedSearch3.CUAHSIFacetedSearch.OntologyElement[] retVal = this.EndGetOntologyElements(result);
            return new object[] {
                    retVal};
        }
        
        private void OnGetOntologyElementsCompleted(object state) {
            if ((this.GetOntologyElementsCompleted != null)) {
                InvokeAsyncCompletedEventArgs e = ((InvokeAsyncCompletedEventArgs)(state));
                this.GetOntologyElementsCompleted(this, new GetOntologyElementsCompletedEventArgs(e.Results, e.Error, e.Cancelled, e.UserState));
            }
        }
        
        public void GetOntologyElementsAsync() {
            this.GetOntologyElementsAsync(null);
        }
        
        public void GetOntologyElementsAsync(object userState) {
            if ((this.onBeginGetOntologyElementsDelegate == null)) {
                this.onBeginGetOntologyElementsDelegate = new BeginOperationDelegate(this.OnBeginGetOntologyElements);
            }
            if ((this.onEndGetOntologyElementsDelegate == null)) {
                this.onEndGetOntologyElementsDelegate = new EndOperationDelegate(this.OnEndGetOntologyElements);
            }
            if ((this.onGetOntologyElementsCompletedDelegate == null)) {
                this.onGetOntologyElementsCompletedDelegate = new System.Threading.SendOrPostCallback(this.OnGetOntologyElementsCompleted);
            }
            base.InvokeAsync(this.onBeginGetOntologyElementsDelegate, null, this.onEndGetOntologyElementsDelegate, this.onGetOntologyElementsCompletedDelegate, userState);
        }
        
        public FacetedSearch3.CUAHSIFacetedSearch.OntologyEnvelope GetOntologyElementsGivenConstraints(FacetedSearch3.CUAHSIFacetedSearch.OntologyElement[] Selections, System.DateTime BeginTime, System.DateTime EndTime, double MinY, double MaxY, double MinX, double MaxX, bool IncludeSpatialResults) {
            return base.Channel.GetOntologyElementsGivenConstraints(Selections, BeginTime, EndTime, MinY, MaxY, MinX, MaxX, IncludeSpatialResults);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        public System.IAsyncResult BeginGetOntologyElementsGivenConstraints(FacetedSearch3.CUAHSIFacetedSearch.OntologyElement[] Selections, System.DateTime BeginTime, System.DateTime EndTime, double MinY, double MaxY, double MinX, double MaxX, bool IncludeSpatialResults, System.AsyncCallback callback, object asyncState) {
            return base.Channel.BeginGetOntologyElementsGivenConstraints(Selections, BeginTime, EndTime, MinY, MaxY, MinX, MaxX, IncludeSpatialResults, callback, asyncState);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        public FacetedSearch3.CUAHSIFacetedSearch.OntologyEnvelope EndGetOntologyElementsGivenConstraints(System.IAsyncResult result) {
            return base.Channel.EndGetOntologyElementsGivenConstraints(result);
        }
        
        private System.IAsyncResult OnBeginGetOntologyElementsGivenConstraints(object[] inValues, System.AsyncCallback callback, object asyncState) {
            FacetedSearch3.CUAHSIFacetedSearch.OntologyElement[] Selections = ((FacetedSearch3.CUAHSIFacetedSearch.OntologyElement[])(inValues[0]));
            System.DateTime BeginTime = ((System.DateTime)(inValues[1]));
            System.DateTime EndTime = ((System.DateTime)(inValues[2]));
            double MinY = ((double)(inValues[3]));
            double MaxY = ((double)(inValues[4]));
            double MinX = ((double)(inValues[5]));
            double MaxX = ((double)(inValues[6]));
            bool IncludeSpatialResults = ((bool)(inValues[7]));
            return this.BeginGetOntologyElementsGivenConstraints(Selections, BeginTime, EndTime, MinY, MaxY, MinX, MaxX, IncludeSpatialResults, callback, asyncState);
        }
        
        private object[] OnEndGetOntologyElementsGivenConstraints(System.IAsyncResult result) {
            FacetedSearch3.CUAHSIFacetedSearch.OntologyEnvelope retVal = this.EndGetOntologyElementsGivenConstraints(result);
            return new object[] {
                    retVal};
        }
        
        private void OnGetOntologyElementsGivenConstraintsCompleted(object state) {
            if ((this.GetOntologyElementsGivenConstraintsCompleted != null)) {
                InvokeAsyncCompletedEventArgs e = ((InvokeAsyncCompletedEventArgs)(state));
                this.GetOntologyElementsGivenConstraintsCompleted(this, new GetOntologyElementsGivenConstraintsCompletedEventArgs(e.Results, e.Error, e.Cancelled, e.UserState));
            }
        }
        
        public void GetOntologyElementsGivenConstraintsAsync(FacetedSearch3.CUAHSIFacetedSearch.OntologyElement[] Selections, System.DateTime BeginTime, System.DateTime EndTime, double MinY, double MaxY, double MinX, double MaxX, bool IncludeSpatialResults) {
            this.GetOntologyElementsGivenConstraintsAsync(Selections, BeginTime, EndTime, MinY, MaxY, MinX, MaxX, IncludeSpatialResults, null);
        }
        
        public void GetOntologyElementsGivenConstraintsAsync(FacetedSearch3.CUAHSIFacetedSearch.OntologyElement[] Selections, System.DateTime BeginTime, System.DateTime EndTime, double MinY, double MaxY, double MinX, double MaxX, bool IncludeSpatialResults, object userState) {
            if ((this.onBeginGetOntologyElementsGivenConstraintsDelegate == null)) {
                this.onBeginGetOntologyElementsGivenConstraintsDelegate = new BeginOperationDelegate(this.OnBeginGetOntologyElementsGivenConstraints);
            }
            if ((this.onEndGetOntologyElementsGivenConstraintsDelegate == null)) {
                this.onEndGetOntologyElementsGivenConstraintsDelegate = new EndOperationDelegate(this.OnEndGetOntologyElementsGivenConstraints);
            }
            if ((this.onGetOntologyElementsGivenConstraintsCompletedDelegate == null)) {
                this.onGetOntologyElementsGivenConstraintsCompletedDelegate = new System.Threading.SendOrPostCallback(this.OnGetOntologyElementsGivenConstraintsCompleted);
            }
            base.InvokeAsync(this.onBeginGetOntologyElementsGivenConstraintsDelegate, new object[] {
                        Selections,
                        BeginTime,
                        EndTime,
                        MinY,
                        MaxY,
                        MinX,
                        MaxX,
                        IncludeSpatialResults}, this.onEndGetOntologyElementsGivenConstraintsDelegate, this.onGetOntologyElementsGivenConstraintsCompletedDelegate, userState);
        }
        
        public FacetedSearch3.CUAHSIFacetedSearch.SeriesCatalogRecord[] GetSeriesGivenConstraints(FacetedSearch3.CUAHSIFacetedSearch.OntologyElement[] Selections, System.DateTime BeginTime, System.DateTime EndTime, double MinY, double MaxY, double MinX, double MaxX) {
            return base.Channel.GetSeriesGivenConstraints(Selections, BeginTime, EndTime, MinY, MaxY, MinX, MaxX);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        public System.IAsyncResult BeginGetSeriesGivenConstraints(FacetedSearch3.CUAHSIFacetedSearch.OntologyElement[] Selections, System.DateTime BeginTime, System.DateTime EndTime, double MinY, double MaxY, double MinX, double MaxX, System.AsyncCallback callback, object asyncState) {
            return base.Channel.BeginGetSeriesGivenConstraints(Selections, BeginTime, EndTime, MinY, MaxY, MinX, MaxX, callback, asyncState);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        public FacetedSearch3.CUAHSIFacetedSearch.SeriesCatalogRecord[] EndGetSeriesGivenConstraints(System.IAsyncResult result) {
            return base.Channel.EndGetSeriesGivenConstraints(result);
        }
        
        private System.IAsyncResult OnBeginGetSeriesGivenConstraints(object[] inValues, System.AsyncCallback callback, object asyncState) {
            FacetedSearch3.CUAHSIFacetedSearch.OntologyElement[] Selections = ((FacetedSearch3.CUAHSIFacetedSearch.OntologyElement[])(inValues[0]));
            System.DateTime BeginTime = ((System.DateTime)(inValues[1]));
            System.DateTime EndTime = ((System.DateTime)(inValues[2]));
            double MinY = ((double)(inValues[3]));
            double MaxY = ((double)(inValues[4]));
            double MinX = ((double)(inValues[5]));
            double MaxX = ((double)(inValues[6]));
            return this.BeginGetSeriesGivenConstraints(Selections, BeginTime, EndTime, MinY, MaxY, MinX, MaxX, callback, asyncState);
        }
        
        private object[] OnEndGetSeriesGivenConstraints(System.IAsyncResult result) {
            FacetedSearch3.CUAHSIFacetedSearch.SeriesCatalogRecord[] retVal = this.EndGetSeriesGivenConstraints(result);
            return new object[] {
                    retVal};
        }
        
        private void OnGetSeriesGivenConstraintsCompleted(object state) {
            if ((this.GetSeriesGivenConstraintsCompleted != null)) {
                InvokeAsyncCompletedEventArgs e = ((InvokeAsyncCompletedEventArgs)(state));
                this.GetSeriesGivenConstraintsCompleted(this, new GetSeriesGivenConstraintsCompletedEventArgs(e.Results, e.Error, e.Cancelled, e.UserState));
            }
        }
        
        public void GetSeriesGivenConstraintsAsync(FacetedSearch3.CUAHSIFacetedSearch.OntologyElement[] Selections, System.DateTime BeginTime, System.DateTime EndTime, double MinY, double MaxY, double MinX, double MaxX) {
            this.GetSeriesGivenConstraintsAsync(Selections, BeginTime, EndTime, MinY, MaxY, MinX, MaxX, null);
        }
        
        public void GetSeriesGivenConstraintsAsync(FacetedSearch3.CUAHSIFacetedSearch.OntologyElement[] Selections, System.DateTime BeginTime, System.DateTime EndTime, double MinY, double MaxY, double MinX, double MaxX, object userState) {
            if ((this.onBeginGetSeriesGivenConstraintsDelegate == null)) {
                this.onBeginGetSeriesGivenConstraintsDelegate = new BeginOperationDelegate(this.OnBeginGetSeriesGivenConstraints);
            }
            if ((this.onEndGetSeriesGivenConstraintsDelegate == null)) {
                this.onEndGetSeriesGivenConstraintsDelegate = new EndOperationDelegate(this.OnEndGetSeriesGivenConstraints);
            }
            if ((this.onGetSeriesGivenConstraintsCompletedDelegate == null)) {
                this.onGetSeriesGivenConstraintsCompletedDelegate = new System.Threading.SendOrPostCallback(this.OnGetSeriesGivenConstraintsCompleted);
            }
            base.InvokeAsync(this.onBeginGetSeriesGivenConstraintsDelegate, new object[] {
                        Selections,
                        BeginTime,
                        EndTime,
                        MinY,
                        MaxY,
                        MinX,
                        MaxX}, this.onEndGetSeriesGivenConstraintsDelegate, this.onGetSeriesGivenConstraintsCompletedDelegate, userState);
        }
        
        public FacetedSearch3.CUAHSIFacetedSearch.SelectionDensityReport GetOntologyElementsDataDensities(System.Collections.Generic.Dictionary<string, FacetedSearch3.CUAHSIFacetedSearch.OntologyElement> Selections, System.DateTime BeginTime, System.DateTime EndTime, double MinY, double MaxY, double MinX, double MaxX, bool IncludeSpatialResults) {
            return base.Channel.GetOntologyElementsDataDensities(Selections, BeginTime, EndTime, MinY, MaxY, MinX, MaxX, IncludeSpatialResults);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        public System.IAsyncResult BeginGetOntologyElementsDataDensities(System.Collections.Generic.Dictionary<string, FacetedSearch3.CUAHSIFacetedSearch.OntologyElement> Selections, System.DateTime BeginTime, System.DateTime EndTime, double MinY, double MaxY, double MinX, double MaxX, bool IncludeSpatialResults, System.AsyncCallback callback, object asyncState) {
            return base.Channel.BeginGetOntologyElementsDataDensities(Selections, BeginTime, EndTime, MinY, MaxY, MinX, MaxX, IncludeSpatialResults, callback, asyncState);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        public FacetedSearch3.CUAHSIFacetedSearch.SelectionDensityReport EndGetOntologyElementsDataDensities(System.IAsyncResult result) {
            return base.Channel.EndGetOntologyElementsDataDensities(result);
        }
        
        private System.IAsyncResult OnBeginGetOntologyElementsDataDensities(object[] inValues, System.AsyncCallback callback, object asyncState) {
            System.Collections.Generic.Dictionary<string, FacetedSearch3.CUAHSIFacetedSearch.OntologyElement> Selections = ((System.Collections.Generic.Dictionary<string, FacetedSearch3.CUAHSIFacetedSearch.OntologyElement>)(inValues[0]));
            System.DateTime BeginTime = ((System.DateTime)(inValues[1]));
            System.DateTime EndTime = ((System.DateTime)(inValues[2]));
            double MinY = ((double)(inValues[3]));
            double MaxY = ((double)(inValues[4]));
            double MinX = ((double)(inValues[5]));
            double MaxX = ((double)(inValues[6]));
            bool IncludeSpatialResults = ((bool)(inValues[7]));
            return this.BeginGetOntologyElementsDataDensities(Selections, BeginTime, EndTime, MinY, MaxY, MinX, MaxX, IncludeSpatialResults, callback, asyncState);
        }
        
        private object[] OnEndGetOntologyElementsDataDensities(System.IAsyncResult result) {
            FacetedSearch3.CUAHSIFacetedSearch.SelectionDensityReport retVal = this.EndGetOntologyElementsDataDensities(result);
            return new object[] {
                    retVal};
        }
        
        private void OnGetOntologyElementsDataDensitiesCompleted(object state) {
            if ((this.GetOntologyElementsDataDensitiesCompleted != null)) {
                InvokeAsyncCompletedEventArgs e = ((InvokeAsyncCompletedEventArgs)(state));
                this.GetOntologyElementsDataDensitiesCompleted(this, new GetOntologyElementsDataDensitiesCompletedEventArgs(e.Results, e.Error, e.Cancelled, e.UserState));
            }
        }
        
        public void GetOntologyElementsDataDensitiesAsync(System.Collections.Generic.Dictionary<string, FacetedSearch3.CUAHSIFacetedSearch.OntologyElement> Selections, System.DateTime BeginTime, System.DateTime EndTime, double MinY, double MaxY, double MinX, double MaxX, bool IncludeSpatialResults) {
            this.GetOntologyElementsDataDensitiesAsync(Selections, BeginTime, EndTime, MinY, MaxY, MinX, MaxX, IncludeSpatialResults, null);
        }
        
        public void GetOntologyElementsDataDensitiesAsync(System.Collections.Generic.Dictionary<string, FacetedSearch3.CUAHSIFacetedSearch.OntologyElement> Selections, System.DateTime BeginTime, System.DateTime EndTime, double MinY, double MaxY, double MinX, double MaxX, bool IncludeSpatialResults, object userState) {
            if ((this.onBeginGetOntologyElementsDataDensitiesDelegate == null)) {
                this.onBeginGetOntologyElementsDataDensitiesDelegate = new BeginOperationDelegate(this.OnBeginGetOntologyElementsDataDensities);
            }
            if ((this.onEndGetOntologyElementsDataDensitiesDelegate == null)) {
                this.onEndGetOntologyElementsDataDensitiesDelegate = new EndOperationDelegate(this.OnEndGetOntologyElementsDataDensities);
            }
            if ((this.onGetOntologyElementsDataDensitiesCompletedDelegate == null)) {
                this.onGetOntologyElementsDataDensitiesCompletedDelegate = new System.Threading.SendOrPostCallback(this.OnGetOntologyElementsDataDensitiesCompleted);
            }
            base.InvokeAsync(this.onBeginGetOntologyElementsDataDensitiesDelegate, new object[] {
                        Selections,
                        BeginTime,
                        EndTime,
                        MinY,
                        MaxY,
                        MinX,
                        MaxX,
                        IncludeSpatialResults}, this.onEndGetOntologyElementsDataDensitiesDelegate, this.onGetOntologyElementsDataDensitiesCompletedDelegate, userState);
        }
        
        public string GetSQLOfNextQuery(FacetedSearch3.CUAHSIFacetedSearch.OntologyElement[] Selections, System.DateTime BeginTime, System.DateTime EndTime, double MinY, double MaxY, double MinX, double MaxX, bool IncludeSpatialResults) {
            return base.Channel.GetSQLOfNextQuery(Selections, BeginTime, EndTime, MinY, MaxY, MinX, MaxX, IncludeSpatialResults);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        public System.IAsyncResult BeginGetSQLOfNextQuery(FacetedSearch3.CUAHSIFacetedSearch.OntologyElement[] Selections, System.DateTime BeginTime, System.DateTime EndTime, double MinY, double MaxY, double MinX, double MaxX, bool IncludeSpatialResults, System.AsyncCallback callback, object asyncState) {
            return base.Channel.BeginGetSQLOfNextQuery(Selections, BeginTime, EndTime, MinY, MaxY, MinX, MaxX, IncludeSpatialResults, callback, asyncState);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        public string EndGetSQLOfNextQuery(System.IAsyncResult result) {
            return base.Channel.EndGetSQLOfNextQuery(result);
        }
        
        private System.IAsyncResult OnBeginGetSQLOfNextQuery(object[] inValues, System.AsyncCallback callback, object asyncState) {
            FacetedSearch3.CUAHSIFacetedSearch.OntologyElement[] Selections = ((FacetedSearch3.CUAHSIFacetedSearch.OntologyElement[])(inValues[0]));
            System.DateTime BeginTime = ((System.DateTime)(inValues[1]));
            System.DateTime EndTime = ((System.DateTime)(inValues[2]));
            double MinY = ((double)(inValues[3]));
            double MaxY = ((double)(inValues[4]));
            double MinX = ((double)(inValues[5]));
            double MaxX = ((double)(inValues[6]));
            bool IncludeSpatialResults = ((bool)(inValues[7]));
            return this.BeginGetSQLOfNextQuery(Selections, BeginTime, EndTime, MinY, MaxY, MinX, MaxX, IncludeSpatialResults, callback, asyncState);
        }
        
        private object[] OnEndGetSQLOfNextQuery(System.IAsyncResult result) {
            string retVal = this.EndGetSQLOfNextQuery(result);
            return new object[] {
                    retVal};
        }
        
        private void OnGetSQLOfNextQueryCompleted(object state) {
            if ((this.GetSQLOfNextQueryCompleted != null)) {
                InvokeAsyncCompletedEventArgs e = ((InvokeAsyncCompletedEventArgs)(state));
                this.GetSQLOfNextQueryCompleted(this, new GetSQLOfNextQueryCompletedEventArgs(e.Results, e.Error, e.Cancelled, e.UserState));
            }
        }
        
        public void GetSQLOfNextQueryAsync(FacetedSearch3.CUAHSIFacetedSearch.OntologyElement[] Selections, System.DateTime BeginTime, System.DateTime EndTime, double MinY, double MaxY, double MinX, double MaxX, bool IncludeSpatialResults) {
            this.GetSQLOfNextQueryAsync(Selections, BeginTime, EndTime, MinY, MaxY, MinX, MaxX, IncludeSpatialResults, null);
        }
        
        public void GetSQLOfNextQueryAsync(FacetedSearch3.CUAHSIFacetedSearch.OntologyElement[] Selections, System.DateTime BeginTime, System.DateTime EndTime, double MinY, double MaxY, double MinX, double MaxX, bool IncludeSpatialResults, object userState) {
            if ((this.onBeginGetSQLOfNextQueryDelegate == null)) {
                this.onBeginGetSQLOfNextQueryDelegate = new BeginOperationDelegate(this.OnBeginGetSQLOfNextQuery);
            }
            if ((this.onEndGetSQLOfNextQueryDelegate == null)) {
                this.onEndGetSQLOfNextQueryDelegate = new EndOperationDelegate(this.OnEndGetSQLOfNextQuery);
            }
            if ((this.onGetSQLOfNextQueryCompletedDelegate == null)) {
                this.onGetSQLOfNextQueryCompletedDelegate = new System.Threading.SendOrPostCallback(this.OnGetSQLOfNextQueryCompleted);
            }
            base.InvokeAsync(this.onBeginGetSQLOfNextQueryDelegate, new object[] {
                        Selections,
                        BeginTime,
                        EndTime,
                        MinY,
                        MaxY,
                        MinX,
                        MaxX,
                        IncludeSpatialResults}, this.onEndGetSQLOfNextQueryDelegate, this.onGetSQLOfNextQueryCompletedDelegate, userState);
        }
        
        public string GetSQLOfSearchQuery(FacetedSearch3.CUAHSIFacetedSearch.OntologyElement[] Selections, System.DateTime BeginTime, System.DateTime EndTime, double MinY, double MaxY, double MinX, double MaxX, bool IncludeSpatialResults) {
            return base.Channel.GetSQLOfSearchQuery(Selections, BeginTime, EndTime, MinY, MaxY, MinX, MaxX, IncludeSpatialResults);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        public System.IAsyncResult BeginGetSQLOfSearchQuery(FacetedSearch3.CUAHSIFacetedSearch.OntologyElement[] Selections, System.DateTime BeginTime, System.DateTime EndTime, double MinY, double MaxY, double MinX, double MaxX, bool IncludeSpatialResults, System.AsyncCallback callback, object asyncState) {
            return base.Channel.BeginGetSQLOfSearchQuery(Selections, BeginTime, EndTime, MinY, MaxY, MinX, MaxX, IncludeSpatialResults, callback, asyncState);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        public string EndGetSQLOfSearchQuery(System.IAsyncResult result) {
            return base.Channel.EndGetSQLOfSearchQuery(result);
        }
        
        private System.IAsyncResult OnBeginGetSQLOfSearchQuery(object[] inValues, System.AsyncCallback callback, object asyncState) {
            FacetedSearch3.CUAHSIFacetedSearch.OntologyElement[] Selections = ((FacetedSearch3.CUAHSIFacetedSearch.OntologyElement[])(inValues[0]));
            System.DateTime BeginTime = ((System.DateTime)(inValues[1]));
            System.DateTime EndTime = ((System.DateTime)(inValues[2]));
            double MinY = ((double)(inValues[3]));
            double MaxY = ((double)(inValues[4]));
            double MinX = ((double)(inValues[5]));
            double MaxX = ((double)(inValues[6]));
            bool IncludeSpatialResults = ((bool)(inValues[7]));
            return this.BeginGetSQLOfSearchQuery(Selections, BeginTime, EndTime, MinY, MaxY, MinX, MaxX, IncludeSpatialResults, callback, asyncState);
        }
        
        private object[] OnEndGetSQLOfSearchQuery(System.IAsyncResult result) {
            string retVal = this.EndGetSQLOfSearchQuery(result);
            return new object[] {
                    retVal};
        }
        
        private void OnGetSQLOfSearchQueryCompleted(object state) {
            if ((this.GetSQLOfSearchQueryCompleted != null)) {
                InvokeAsyncCompletedEventArgs e = ((InvokeAsyncCompletedEventArgs)(state));
                this.GetSQLOfSearchQueryCompleted(this, new GetSQLOfSearchQueryCompletedEventArgs(e.Results, e.Error, e.Cancelled, e.UserState));
            }
        }
        
        public void GetSQLOfSearchQueryAsync(FacetedSearch3.CUAHSIFacetedSearch.OntologyElement[] Selections, System.DateTime BeginTime, System.DateTime EndTime, double MinY, double MaxY, double MinX, double MaxX, bool IncludeSpatialResults) {
            this.GetSQLOfSearchQueryAsync(Selections, BeginTime, EndTime, MinY, MaxY, MinX, MaxX, IncludeSpatialResults, null);
        }
        
        public void GetSQLOfSearchQueryAsync(FacetedSearch3.CUAHSIFacetedSearch.OntologyElement[] Selections, System.DateTime BeginTime, System.DateTime EndTime, double MinY, double MaxY, double MinX, double MaxX, bool IncludeSpatialResults, object userState) {
            if ((this.onBeginGetSQLOfSearchQueryDelegate == null)) {
                this.onBeginGetSQLOfSearchQueryDelegate = new BeginOperationDelegate(this.OnBeginGetSQLOfSearchQuery);
            }
            if ((this.onEndGetSQLOfSearchQueryDelegate == null)) {
                this.onEndGetSQLOfSearchQueryDelegate = new EndOperationDelegate(this.OnEndGetSQLOfSearchQuery);
            }
            if ((this.onGetSQLOfSearchQueryCompletedDelegate == null)) {
                this.onGetSQLOfSearchQueryCompletedDelegate = new System.Threading.SendOrPostCallback(this.OnGetSQLOfSearchQueryCompleted);
            }
            base.InvokeAsync(this.onBeginGetSQLOfSearchQueryDelegate, new object[] {
                        Selections,
                        BeginTime,
                        EndTime,
                        MinY,
                        MaxY,
                        MinX,
                        MaxX,
                        IncludeSpatialResults}, this.onEndGetSQLOfSearchQueryDelegate, this.onGetSQLOfSearchQueryCompletedDelegate, userState);
        }
        
        public string GetSQLOfNextDensityQuery(FacetedSearch3.CUAHSIFacetedSearch.OntologyElement[] Selections, System.DateTime BeginTime, System.DateTime EndTime, double MinY, double MaxY, double MinX, double MaxX, bool IncludeSpatialResults) {
            return base.Channel.GetSQLOfNextDensityQuery(Selections, BeginTime, EndTime, MinY, MaxY, MinX, MaxX, IncludeSpatialResults);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        public System.IAsyncResult BeginGetSQLOfNextDensityQuery(FacetedSearch3.CUAHSIFacetedSearch.OntologyElement[] Selections, System.DateTime BeginTime, System.DateTime EndTime, double MinY, double MaxY, double MinX, double MaxX, bool IncludeSpatialResults, System.AsyncCallback callback, object asyncState) {
            return base.Channel.BeginGetSQLOfNextDensityQuery(Selections, BeginTime, EndTime, MinY, MaxY, MinX, MaxX, IncludeSpatialResults, callback, asyncState);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        public string EndGetSQLOfNextDensityQuery(System.IAsyncResult result) {
            return base.Channel.EndGetSQLOfNextDensityQuery(result);
        }
        
        private System.IAsyncResult OnBeginGetSQLOfNextDensityQuery(object[] inValues, System.AsyncCallback callback, object asyncState) {
            FacetedSearch3.CUAHSIFacetedSearch.OntologyElement[] Selections = ((FacetedSearch3.CUAHSIFacetedSearch.OntologyElement[])(inValues[0]));
            System.DateTime BeginTime = ((System.DateTime)(inValues[1]));
            System.DateTime EndTime = ((System.DateTime)(inValues[2]));
            double MinY = ((double)(inValues[3]));
            double MaxY = ((double)(inValues[4]));
            double MinX = ((double)(inValues[5]));
            double MaxX = ((double)(inValues[6]));
            bool IncludeSpatialResults = ((bool)(inValues[7]));
            return this.BeginGetSQLOfNextDensityQuery(Selections, BeginTime, EndTime, MinY, MaxY, MinX, MaxX, IncludeSpatialResults, callback, asyncState);
        }
        
        private object[] OnEndGetSQLOfNextDensityQuery(System.IAsyncResult result) {
            string retVal = this.EndGetSQLOfNextDensityQuery(result);
            return new object[] {
                    retVal};
        }
        
        private void OnGetSQLOfNextDensityQueryCompleted(object state) {
            if ((this.GetSQLOfNextDensityQueryCompleted != null)) {
                InvokeAsyncCompletedEventArgs e = ((InvokeAsyncCompletedEventArgs)(state));
                this.GetSQLOfNextDensityQueryCompleted(this, new GetSQLOfNextDensityQueryCompletedEventArgs(e.Results, e.Error, e.Cancelled, e.UserState));
            }
        }
        
        public void GetSQLOfNextDensityQueryAsync(FacetedSearch3.CUAHSIFacetedSearch.OntologyElement[] Selections, System.DateTime BeginTime, System.DateTime EndTime, double MinY, double MaxY, double MinX, double MaxX, bool IncludeSpatialResults) {
            this.GetSQLOfNextDensityQueryAsync(Selections, BeginTime, EndTime, MinY, MaxY, MinX, MaxX, IncludeSpatialResults, null);
        }
        
        public void GetSQLOfNextDensityQueryAsync(FacetedSearch3.CUAHSIFacetedSearch.OntologyElement[] Selections, System.DateTime BeginTime, System.DateTime EndTime, double MinY, double MaxY, double MinX, double MaxX, bool IncludeSpatialResults, object userState) {
            if ((this.onBeginGetSQLOfNextDensityQueryDelegate == null)) {
                this.onBeginGetSQLOfNextDensityQueryDelegate = new BeginOperationDelegate(this.OnBeginGetSQLOfNextDensityQuery);
            }
            if ((this.onEndGetSQLOfNextDensityQueryDelegate == null)) {
                this.onEndGetSQLOfNextDensityQueryDelegate = new EndOperationDelegate(this.OnEndGetSQLOfNextDensityQuery);
            }
            if ((this.onGetSQLOfNextDensityQueryCompletedDelegate == null)) {
                this.onGetSQLOfNextDensityQueryCompletedDelegate = new System.Threading.SendOrPostCallback(this.OnGetSQLOfNextDensityQueryCompleted);
            }
            base.InvokeAsync(this.onBeginGetSQLOfNextDensityQueryDelegate, new object[] {
                        Selections,
                        BeginTime,
                        EndTime,
                        MinY,
                        MaxY,
                        MinX,
                        MaxX,
                        IncludeSpatialResults}, this.onEndGetSQLOfNextDensityQueryDelegate, this.onGetSQLOfNextDensityQueryCompletedDelegate, userState);
        }
    }
}
